import logger from "@/lib/logger";

export interface LinkedInExtras {
  headline?: string;
  vanityName?: string;
  linkedInUrl?: string;
  location?: string;
  firstName?: string;
  lastName?: string;
}

/**
 * Try to fetch additional profile data from LinkedIn REST API using the
 * OAuth access token. Returns whatever fields are available — if the app
 * only has the OIDC product, the REST API calls will return 403 and we
 * gracefully return an empty object.
 *
 * With `r_liteprofile` → firstName, lastName, profilePicture
 * With `r_basicprofile` → above + headline, vanityName, geoLocation
 */
export async function fetchLinkedInExtras(
  accessToken: string,
): Promise<LinkedInExtras> {
  const result: LinkedInExtras = {};

  try {
    // Try /v2/me with r_basicprofile projections
    const res = await fetch(
      "https://api.linkedin.com/v2/me?projection=(localizedFirstName,localizedLastName,localizedHeadline,vanityName)",
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "X-Restli-Protocol-Version": "2.0.0",
        },
      },
    );

    if (res.ok) {
      const data = await res.json();

      if (data.localizedFirstName) result.firstName = data.localizedFirstName;
      if (data.localizedLastName) result.lastName = data.localizedLastName;

      if (data.localizedHeadline) {
        result.headline = data.localizedHeadline;
      } else if (data.headline?.localized) {
        // Fallback: pick first locale value
        const locales = Object.values(data.headline.localized) as string[];
        if (locales[0]) result.headline = locales[0];
      }

      if (data.vanityName) {
        result.vanityName = data.vanityName;
        result.linkedInUrl = `https://www.linkedin.com/in/${data.vanityName}`;
      }
    }
  } catch (err) {
    logger.debug({ err }, "LinkedIn REST /v2/me not available — OIDC-only app");
  }

  // Try location separately (may require additional projection)
  try {
    const geoRes = await fetch(
      "https://api.linkedin.com/v2/me?projection=(geoLocation(geo~,autoGenerated))",
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "X-Restli-Protocol-Version": "2.0.0",
        },
      },
    );

    if (geoRes.ok) {
      const geoData = await geoRes.json();
      const geoName =
        geoData?.geoLocation?.["geo~"]?.defaultLocalizedName?.value;
      if (geoName) result.location = geoName;
    }
  } catch {
    // Location not available — fine
  }

  return result;
}
