const fs = require('fs');
const path = 'c:\\Users\\moham\\OneDrive\\Desktop\\Mployedin\\mployedin\\src\\components\\shared\\ResumeViewerModal.tsx';
const content = fs.readFileSync(path, 'utf8');
const lines = content.split('\n');
console.log('Total lines:', lines.length);
console.log('Line 440:', JSON.stringify(lines[439]));
console.log('Line 441:', JSON.stringify(lines[440]));
const truncated = lines.slice(0, 440).join('\n');
fs.writeFileSync(path, truncated, 'utf8');
console.log('Done. Written', truncated.split('\n').length, 'lines');
