/**
 * Client-side export utilities: CSV, Excel (xlsx), PDF (jspdf).
 */

export interface ExportColumn<T> {
  header: string;
  key: keyof T;
  formatter?: (value: T[keyof T], row: T) => string;
}

/* ── helpers ─────────────────────────────────────────── */

function resolveValue<T extends Record<string, unknown>>(
  row: T,
  col: ExportColumn<T>,
): string {
  const raw = row[col.key as string];
  if (col.formatter) return col.formatter(raw as T[keyof T], row);
  return raw == null ? "" : String(raw);
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/* ── CSV ─────────────────────────────────────────────── */

export function exportCSV<T extends Record<string, unknown>>(
  data: T[],
  columns: ExportColumn<T>[],
  filename = "export.csv",
): void {
  const header = columns.map((c) => `"${c.header}"`).join(",");
  const rows = data.map((row) =>
    columns
      .map((col) => {
        const val = resolveValue(row, col);
        return `"${String(val).replace(/"/g, '""')}"`;
      })
      .join(","),
  );

  const csv = [header, ...rows].join("\n");
  const blob = new Blob(["\uFEFF" + csv], {
    type: "text/csv;charset=utf-8;",
  });
  triggerDownload(blob, filename);
}

/* ── Excel (xlsx) ────────────────────────────────────── */

export async function exportExcel<T extends Record<string, unknown>>(
  data: T[],
  columns: ExportColumn<T>[],
  filename = "export.xlsx",
  sheetName = "Sheet1",
): Promise<void> {
  const XLSX = await import("xlsx");
  const rows = data.map((row) => {
    const obj: Record<string, string> = {};
    columns.forEach((col) => {
      obj[col.header] = resolveValue(row, col);
    });
    return obj;
  });
  const ws = XLSX.utils.json_to_sheet(rows);
  // auto-width columns
  ws["!cols"] = columns.map((c) => ({ wch: Math.max(c.header.length + 2, 14) }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName);
  XLSX.writeFile(wb, filename);
}

/* ── PDF (jspdf + autotable) ─────────────────────────── */

export async function exportPdf<T extends Record<string, unknown>>(
  data: T[],
  columns: ExportColumn<T>[],
  filename = "export.pdf",
  title = "Export",
): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const doc = new jsPDF({ orientation: columns.length > 6 ? "landscape" : "portrait" });

  // Title
  doc.setFontSize(16);
  doc.text(title, 14, 18);
  doc.setFontSize(9);
  doc.setTextColor(130);
  doc.text(
    `Generated by MPLOYEDIN · ${new Date().toLocaleString("en-AE")}`,
    14,
    25,
  );

  const head = [columns.map((c) => c.header)];
  const body = data.map((row) => columns.map((col) => resolveValue(row, col)));

  autoTable(doc, {
    startY: 30,
    head,
    body,
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [13, 111, 216], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: 14, right: 14 },
  });

  doc.save(filename);
}

/* ── JSON ────────────────────────────────────────────── */

export function exportJSON<T>(data: T[], filename = "export.json"): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: "application/json",
  });
  triggerDownload(blob, filename);
}

/* ── Print to PDF (legacy) ───────────────────────────── */

export function exportPrint<T extends Record<string, unknown>>(
  data: T[],
  columns: ExportColumn<T>[],
  title = "Export",
): void {
  const rows = data
    .map(
      (row) =>
        `<tr>${columns
          .map((col) => {
            const val = resolveValue(row, col);
            return `<td style="padding:6px 10px;border:1px solid #ddd;font-size:12px">${val}</td>`;
          })
          .join("")}</tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html><html><head>
    <title>${title}</title>
    <style>
      body{font-family:sans-serif;padding:24px}
      h2{margin-bottom:12px}
      table{width:100%;border-collapse:collapse}
      th{background:#0D6FD8;color:white;padding:8px 10px;font-size:12px;text-align:left;border:1px solid #ccc}
    </style>
  </head><body>
    <h2>${title}</h2>
    <table>
      <thead><tr>${columns.map((c) => `<th>${c.header}</th>`).join("")}</tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <p style="font-size:10px;color:#999;margin-top:16px">Generated by MPLOYEDIN · ${new Date().toLocaleString("en-AE")}</p>
  </body></html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.print();
}

/* ── Convenience formatters ──────────────────────────── */

export function fmtDate(val: unknown): string {
  if (!val) return "—";
  return new Date(String(val)).toLocaleDateString("en-AE");
}

export function fmtCurrency(val: unknown, currency = "AED"): string {
  if (!val) return "—";
  return `${Number(val).toLocaleString()} ${currency}`;
}
