/**
 * Client-side CSV + print-to-PDF export utilities.
 * Zero dependencies — works in any browser.
 */

export interface ExportColumn<T> {
  header: string;
  key: keyof T;
  formatter?: (value: T[keyof T], row: T) => string;
}

/**
 * Export an array of objects to a CSV file and trigger browser download.
 */
export function exportCSV<T extends Record<string, unknown>>(
  data: T[],
  columns: ExportColumn<T>[],
  filename = "export.csv"
): void {
  const header = columns.map(c => `"${c.header}"`).join(",");
  const rows = data.map(row =>
    columns.map(col => {
      const raw = row[col.key as string];
      const val = col.formatter
        ? col.formatter(raw as T[keyof T], row)
        : raw == null ? "" : String(raw);
      // Escape quotes
      return `"${String(val).replace(/"/g, '""')}"`;
    }).join(",")
  );

  const csv = [header, ...rows].join("\n");
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" }); // BOM for Excel
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Export an array of objects to a JSON file.
 */
export function exportJSON<T>(data: T[], filename = "export.json"): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Open a print dialog with a formatted table for the provided data.
 * This is the "print to PDF" pathway.
 */
export function exportPrint<T extends Record<string, unknown>>(
  data: T[],
  columns: ExportColumn<T>[],
  title = "Export"
): void {
  const rows = data.map(row =>
    `<tr>${columns.map(col => {
      const raw = row[col.key as string];
      const val = col.formatter
        ? col.formatter(raw as T[keyof T], row)
        : raw == null ? "" : String(raw);
      return `<td style="padding:6px 10px;border:1px solid #ddd;font-size:12px">${val}</td>`;
    }).join("")}</tr>`
  ).join("");

  const html = `<!DOCTYPE html><html><head>
    <title>${title}</title>
    <style>
      body{font-family:sans-serif;padding:24px}
      h2{margin-bottom:12px}
      table{width:100%;border-collapse:collapse}
      th{background:#0D6FD8;color:white;padding:8px 10px;font-size:12px;text-align:left;border:1px solid #ccc}
    </style>
  </head><body>
    <h2>${title}</h2>
    <table>
      <thead><tr>${columns.map(c => `<th>${c.header}</th>`).join("")}</tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <p style="font-size:10px;color:#999;margin-top:16px">Generated by MPLOYEDIN · ${new Date().toLocaleString("en-AE")}</p>
  </body></html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.print();
}

/** Convenience: format a date value for export */
export function fmtDate(val: unknown): string {
  if (!val) return "—";
  return new Date(String(val)).toLocaleDateString("en-AE");
}

/** Convenience: format a currency value */
export function fmtCurrency(val: unknown, currency = "AED"): string {
  if (!val) return "—";
  return `${Number(val).toLocaleString()} ${currency}`;
}
