import type { UserRole } from "@/models/User";
import type { IconName } from "./iconRegistry";

/** Resources in the system */
export type Resource = string;

export interface NavItem {
  title: string;
  titleAr: string;
  href: string;
  /** Plain icon name — resolved to a Lucide component inside Client Components via getIcon() */
  icon: IconName;
  badge?: string;
  /** Short description shown in command menu */
  description?: string;
  descriptionAr?: string;
  /** Optional group label for grouping children in the submenu panel */
  group?: string;
  groupAr?: string;
  children?: NavItem[];
}

export interface NavGroup {
  label?: string;
  labelAr?: string;
  items: NavItem[];
}

function buildNav(locale: string): Record<UserRole, NavGroup[]> {
  const p = (path: string) => `/${locale}${path}`;

  return {
    admin: [
      {
        items: [
          {
            title: "Dashboard",
            titleAr: "لوحة التحكم",
            href: p("/admin"),
            icon: "LayoutDashboard",
            description: "Overview & key metrics",
            descriptionAr: "نظرة عامة والمقاييس الرئيسية",
          },
          {
            title: "Recruitment",
            titleAr: "التوظيف",
            href: p("/admin/jobs"),
            icon: "Briefcase",
            description: "Manage the hiring pipeline",
            descriptionAr: "إدارة عملية التوظيف",
            children: [
              {
                title: "Jobs",
                titleAr: "الوظائف",
                href: p("/admin/jobs"),
                icon: "Briefcase",
                description: "Manage job listings",
                descriptionAr: "إدارة الوظائف المنشورة",
              },
              {
                title: "Job Approvals",
                titleAr: "الموافقات على الوظائف",
                href: p("/admin/approvals"),
                icon: "CheckCircle",
                description: "Review & approve pending jobs",
                descriptionAr: "مراجعة الوظائف المعلقة والموافقة عليها",
              },
              {
                title: "Applications",
                titleAr: "الطلبات",
                href: p("/admin/applications"),
                icon: "FileText",
                description: "Review candidate applications",
                descriptionAr: "مراجعة طلبات المرشحين",
              },
              {
                title: "Interviews",
                titleAr: "المقابلات",
                href: p("/admin/interviews"),
                icon: "Calendar",
                description: "Schedule & track interviews",
                descriptionAr: "جدولة وتتبع المقابلات",
              },
              {
                title: "Placements",
                titleAr: "التوظيفات",
                href: p("/admin/placements"),
                icon: "UserCheck",
                description: "Confirmed hires & placements",
                descriptionAr: "التعيينات المؤكدة",
              },
            ],
          },
          {
            title: "People",
            titleAr: "الأشخاص",
            href: p("/admin/employers"),
            icon: "Users",
            description: "Manage all users & accounts",
            descriptionAr: "إدارة جميع المستخدمين والحسابات",
            children: [
              {
                title: "Employers",
                titleAr: "أصحاب العمل",
                href: p("/admin/employers"),
                icon: "Building2",
                description: "Company accounts & profiles",
                descriptionAr: "حسابات وملفات الشركات",
                group: "Accounts",
                groupAr: "الحسابات",
              },
              {
                title: "Job Seekers",
                titleAr: "الباحثون عن عمل",
                href: p("/admin/job-seekers"),
                icon: "UserSearch",
                description: "Candidate profiles & CVs",
                descriptionAr: "ملفات المرشحين والسير الذاتية",
                group: "Accounts",
                groupAr: "الحسابات",
              },
              {
                title: "Agents",
                titleAr: "الوكلاء",
                href: p("/admin/agents"),
                icon: "Star",
                description: "Recruitment agents & regions",
                descriptionAr: "وكلاء التوظيف والمناطق",
                group: "Workforce",
                groupAr: "القوى العاملة",
              },
              {
                title: "Super Agents",
                titleAr: "الوكلاء الكبار",
                href: p("/admin/super-agents"),
                icon: "Shield",
                description: "Agent managers & team leads",
                descriptionAr: "مديرو الوكلاء وقادة الفرق",
                group: "Workforce",
                groupAr: "القوى العاملة",
              },
              {
                title: "Users",
                titleAr: "المستخدمون",
                href: p("/admin/users"),
                icon: "UserCog",
                description: "System users & permissions",
                descriptionAr: "مستخدمو النظام والأذونات",
                group: "Workforce",
                groupAr: "القوى العاملة",
              },
              {
                title: "Territory",
                titleAr: "المناطق",
                href: p("/admin/territory"),
                icon: "MapPin",
                description: "Geographic territories & lead routing",
                descriptionAr: "المناطق الجغرافية وتوجيه العملاء المحتملين",
                group: "Workforce",
                groupAr: "القوى العاملة",
              },
              {
                title: "Referral Links",
                titleAr: "روابط الإحالة",
                href: p("/admin/referral-links"),
                icon: "Link2",
                description: "All referral links & analytics",
                descriptionAr: "جميع روابط الإحالة والتحليلات",
                group: "Marketing",
                groupAr: "التسويق",
              },
            ],
          },
          {
            title: "Finance",
            titleAr: "المالية",
            href: p("/admin/commissions"),
            icon: "DollarSign",
            description: "Commissions, subscriptions & payments",
            descriptionAr: "العمولات والاشتراكات والمدفوعات",
            children: [
              {
                title: "Commissions",
                titleAr: "العمولات",
                href: p("/admin/commissions"),
                icon: "DollarSign",
                description: "Track & manage commissions",
                descriptionAr: "تتبع وإدارة العمولات",
              },
              {
                title: "Invoices",
                titleAr: "الفواتير",
                href: p("/admin/invoices"),
                icon: "ReceiptText",
                description: "Recruitment & subscription invoices",
                descriptionAr: "فواتير التوظيف والاشتراكات",
              },
              {
                title: "Subscription Plans",
                titleAr: "خطط الاشتراك",
                href: p("/admin/subscription-plans"),
                icon: "Crown",
                description: "Manage subscription tiers & features",
                descriptionAr: "إدارة مستويات الاشتراك والميزات",
              },
              {
                title: "Subscriptions",
                titleAr: "الاشتراكات",
                href: p("/admin/subscriptions"),
                icon: "CreditCard",
                description: "Assign & manage user subscriptions",
                descriptionAr: "تعيين وإدارة اشتراكات المستخدمين",
              },
              {
                title: "Subscription Dashboard",
                titleAr: "لوحة الاشتراكات",
                href: p("/admin/subscription-dashboard"),
                icon: "BarChart2",
                description: "Overview, revenue & activity stats",
                descriptionAr: "نظرة عامة والإيرادات وإحصائيات النشاط",
              },
              {
                title: "Targets",
                titleAr: "الأهداف",
                href: p("/admin/target-management"),
                icon: "Target",
                description: "Enterprise target profiles & analytics",
                descriptionAr: "ملفات الأهداف المتقدمة والتحليلات",
              },
              {
                title: "Target Report",
                titleAr: "تقرير الأهداف",
                href: p("/admin/target-report"),
                icon: "FileText",
                description: "Consolidated target performance report",
                descriptionAr: "تقرير أداء الأهداف الموحد",
              },
              {
                title: "Commission Report",
                titleAr: "تقرير العمولات",
                href: p("/admin/commissions-report"),
                icon: "BarChart2",
                description: "Aggregated commission analytics across all agents",
                descriptionAr: "تحليلات العمولات الموحدة لجميع الوكلاء",
              },
            ],
          },
          {
            title: "CMS / Content",
            titleAr: "إدارة المحتوى",
            href: p("/admin/cms"),
            icon: "PanelsTopLeft",
            description: "Manage website content",
            descriptionAr: "إدارة محتوى الموقع",
            children: [
              {
                title: "CMS Overview",
                titleAr: "نظرة عامة",
                href: p("/admin/cms"),
                icon: "PanelsTopLeft",
                description: "Content management dashboard",
                descriptionAr: "لوحة إدارة المحتوى",
                group: "Overview",
                groupAr: "نظرة عامة",
              },
              {
                title: "FAQs",
                titleAr: "الأسئلة الشائعة",
                href: p("/admin/cms/faqs"),
                icon: "HelpCircle",
                description: "Frequently asked questions",
                descriptionAr: "الأسئلة المتداولة",
                group: "Content",
                groupAr: "المحتوى",
              },
              {
                title: "Blog Posts",
                titleAr: "المقالات",
                href: p("/admin/cms/blogs"),
                icon: "Newspaper",
                description: "Articles & news posts",
                descriptionAr: "المقالات والأخبار",
                group: "Content",
                groupAr: "المحتوى",
              },
              {
                title: "Testimonials",
                titleAr: "شهادات العملاء",
                href: p("/admin/cms/testimonials"),
                icon: "Quote",
                description: "Client success stories",
                descriptionAr: "قصص نجاح العملاء",
                group: "Content",
                groupAr: "المحتوى",
              },
              {
                title: "Banners",
                titleAr: "البانرات",
                href: p("/admin/cms/banners"),
                icon: "Image",
                description: "Homepage & promo banners",
                descriptionAr: "بانرات الصفحة الرئيسية",
                group: "Media",
                groupAr: "الوسائط",
              },
              {
                title: "Videos",
                titleAr: "الفيديوهات",
                href: p("/admin/cms/videos"),
                icon: "Video",
                description: "Video content library",
                descriptionAr: "مكتبة محتوى الفيديو",
                group: "Media",
                groupAr: "الوسائط",
              },
              {
                title: "Static Pages",
                titleAr: "الصفحات الثابتة",
                href: p("/admin/cms/static-pages"),
                icon: "FileText",
                description: "Privacy, terms & custom pages",
                descriptionAr: "الخصوصية والشروط والصفحات المخصصة",
                group: "Pages",
                groupAr: "الصفحات",
              },
              {
                title: "Contact Inbox",
                titleAr: "صندوق الرسائل",
                href: p("/admin/cms/contact-submissions"),
                icon: "Mail",
                description: "Contact form submissions",
                descriptionAr: "رسائل نموذج الاتصال",
                group: "Pages",
                groupAr: "الصفحات",
              },

            ],
          },
          {
            title: "Platform Data",
            titleAr: "بيانات المنصة",
            href: p("/admin/job-attributes"),
            icon: "SlidersHorizontal",
            description: "Configure job and location data",
            descriptionAr: "إعداد بيانات الوظائف والمواقع",
            // Only categories with a live consumer belong here — see categoryResolver.ts
            children: [
              {
                title: "Marital Status",
                titleAr: "الحالة الاجتماعية",
                href: p("/admin/job-attributes/marital-statuses"),
                icon: "Heart",
                description: "Marital status options",
                descriptionAr: "خيارات الحالة الاجتماعية",
                group: "Personal",
                groupAr: "شخصي",
              },
              {
                title: "Major Subjects",
                titleAr: "التخصصات الرئيسية",
                href: p("/admin/job-attributes/major-subjects"),
                icon: "GraduationCap",
                description: "Fields of study",
                descriptionAr: "مجالات الدراسة",
                group: "Education",
                groupAr: "التعليم",
              },
              {
                title: "Job Skills",
                titleAr: "المهارات الوظيفية",
                href: p("/admin/job-attributes/job-skills"),
                icon: "Wrench",
                description: "Skills & competency tags",
                descriptionAr: "علامات المهارات والكفاءات",
                group: "Employment",
                groupAr: "التوظيف",
              },
              {
                title: "Industries",
                titleAr: "الصناعات",
                href: p("/admin/job-attributes/industries"),
                icon: "Factory",
                description: "Industry sector list",
                descriptionAr: "قائمة القطاعات الصناعية",
                group: "Classification",
                groupAr: "التصنيف",
              },
              {
                title: "Genders",
                titleAr: "الجنس",
                href: p("/admin/job-attributes/genders"),
                icon: "UserCircle",
                description: "Gender preference options",
                descriptionAr: "خيارات تفضيل الجنس",
                group: "Personal",
                groupAr: "شخصي",
              },
              {
                title: "Countries",
                titleAr: "الدول",
                href: p("/admin/location-data/countries"),
                icon: "Globe",
                description: "Manage country list",
                descriptionAr: "إدارة قائمة الدول",
                group: "Locations",
                groupAr: "المواقع",
              },
              {
                title: "States",
                titleAr: "المحافظات",
                href: p("/admin/location-data/states"),
                icon: "Map",
                description: "States & provinces",
                descriptionAr: "المحافظات والأقاليم",
                group: "Locations",
                groupAr: "المواقع",
              },
              {
                title: "Cities",
                titleAr: "المدن",
                href: p("/admin/location-data/cities"),
                icon: "MapPin",
                description: "City directory",
                descriptionAr: "دليل المدن",
                group: "Locations",
                groupAr: "المواقع",
              },
            ],
          },
          {
            title: "Reports & Analytics",
            titleAr: "التقارير والتحليلات",
            href: p("/admin/reports"),
            icon: "BarChart2",
            description: "Reports, analytics & activity logs",
            descriptionAr: "التقارير والتحليلات وسجلات النشاط",
            children: [
              {
                title: "Reports",
                titleAr: "التقارير",
                href: p("/admin/reports"),
                icon: "BarChart2",
                description: "Analytics & reports",
                descriptionAr: "التحليلات والتقارير",
              },
              {
                title: "Analytics",
                titleAr: "التحليلات",
                href: p("/admin/analytics"),
                icon: "TrendingUp",
                description: "Platform usage analytics",
                descriptionAr: "تحليلات استخدام المنصة",
              },
              {
                title: "Audit Logs",
                titleAr: "سجلات التدقيق",
                href: p("/admin/audit-logs"),
                icon: "ClipboardList",
                description: "Track all system activity",
                descriptionAr: "تتبع جميع أنشطة النظام",
              },
              {
                title: "Activity Timeline",
                titleAr: "سجل الأنشطة",
                href: p("/admin/activity-timeline"),
                icon: "History",
                description: "Visual timeline of all actions",
                descriptionAr: "سجل مرئي لجميع الإجراءات",
              },
            ],
          },
          {
            title: "System",
            titleAr: "النظام",
            href: p("/admin/settings"),
            icon: "Settings",
            description: "Settings & configuration",
            descriptionAr: "الإعدادات والتكوين",
            children: [
              {
                title: "Settings",
                titleAr: "الإعدادات",
                href: p("/admin/settings"),
                icon: "Settings",
                description: "Platform configuration",
                descriptionAr: "إعدادات المنصة",
                group: "Configuration",
                groupAr: "التكوين",
              },
              {
                title: "Communications",
                titleAr: "الاتصالات",
                href: p("/admin/communications"),
                icon: "MessageSquare",
                description: "Email & notification logs",
                descriptionAr: "سجلات البريد والإشعارات",
                group: "Configuration",
                groupAr: "التكوين",
              },
              {
                title: "Notification System",
                titleAr: "نظام الإشعارات",
                href: p("/admin/settings/notifications"),
                icon: "Bell",
                description: "Email automation & monitoring",
                descriptionAr: "أتمتة البريد الإلكتروني والمراقبة",
                group: "Configuration",
                groupAr: "التكوين",
              },
              {
                title: "Webhooks",
                titleAr: "الويب هوك",
                href: p("/admin/webhooks"),
                icon: "Link2",
                description: "Outbound webhook integrations",
                descriptionAr: "تكاملات الويب هوك الصادرة",
                group: "Configuration",
                groupAr: "التكوين",
              },

              {
                title: "Workflow Templates",
                titleAr: "قوالب سير العمل",
                href: p("/admin/workflow-templates"),
                icon: "GitBranch",
                description: "Manage hiring workflow presets",
                descriptionAr: "إدارة قوالب سير عمل التوظيف",
                group: "Automation",
                groupAr: "الأتمتة",
              },
              {
                title: "Matching Weight Templates",
                titleAr: "قوالب أوزان المطابقة",
                href: p("/admin/matching-weight-templates"),
                icon: "Scale",
                description: "Manage matching weight presets",
                descriptionAr: "إدارة قوالب أوزان المطابقة",
                group: "Automation",
                groupAr: "الأتمتة",
              },
              {
                title: "GDPR / Data Privacy",
                titleAr: "حماية البيانات",
                href: p("/admin/gdpr"),
                icon: "ShieldCheck",
                description: "Data requests, consent & retention",
                descriptionAr: "طلبات البيانات والموافقة والاحتفاظ",
                group: "Compliance",
                groupAr: "الامتثال",
              },
              {
                title: "Bulk Import",
                titleAr: "استيراد جماعي",
                href: p("/admin/bulk-import"),
                icon: "Upload",
                description: "CSV import for users & jobs",
                descriptionAr: "استيراد CSV للمستخدمين والوظائف",
                group: "Data",
                groupAr: "البيانات",
              },
              {
                title: "System Health",
                titleAr: "صحة النظام",
                href: p("/admin/system-health"),
                icon: "Activity",
                description: "Platform monitoring & diagnostics",
                descriptionAr: "مراقبة المنصة والتشخيص",
                group: "Operations",
                groupAr: "العمليات",
              },
              {
                title: "Impersonate User",
                titleAr: "انتحال هوية مستخدم",
                href: p("/admin/impersonate"),
                icon: "UserCheck",
                description: "Sign in as another user for support",
                descriptionAr: "تسجيل الدخول كمستخدم آخر للدعم",
                group: "Operations",
                groupAr: "العمليات",
              },
            ],
          },
          {
            title: "Exhibitions",
            titleAr: "المعارض",
            href: p("/admin/exhibitions"),
            icon: "CalendarDays",
            description: "Requests, performance & resources",
            descriptionAr: "الطلبات والأداء والموارد",
            children: [
              {
                title: "Review Requests",
                titleAr: "مراجعة الطلبات",
                href: p("/admin/exhibitions"),
                icon: "CalendarDays",
                description: "Manage exhibition requests",
                descriptionAr: "إدارة طلبات المعارض",
              },
              {
                title: "Check Performance",
                titleAr: "مراجعة الأداء",
                href: p("/admin/exhibitions/analytics"),
                icon: "BarChart2",
                description: "Exhibition performance reports",
                descriptionAr: "تقارير أداء المعارض",
              },
              {
                title: "Manage Resources",
                titleAr: "إدارة الموارد",
                href: p("/admin/resources"),
                icon: "FolderOpen",
                description: "Upload and manage exhibition resources",
                descriptionAr: "رفع وإدارة موارد المعارض",
              },
            ],
          },
          {
            title: "Communication",
            titleAr: "التواصل",
            href: p("/admin/messages"),
            icon: "MessageSquare",
            description: "Messages, support & notifications",
            descriptionAr: "الرسائل والدعم والإشعارات",
            children: [
              {
                title: "Open Messages",
                titleAr: "فتح الرسائل",
                href: p("/admin/messages"),
                icon: "MessageSquare",
                description: "Messages and support tickets",
                descriptionAr: "الرسائل وتذاكر الدعم",
              },
            ],
          },
        ],
      },
    ],

    super_agent: [
      {
        items: [
          {
            title: "Dashboard",
            titleAr: "لوحة التحكم",
            href: p("/super-agent"),
            icon: "LayoutDashboard",
            description: "Overview & key metrics",
            descriptionAr: "نظرة عامة والمقاييس الرئيسية",
          },
          {
            title: "Team",
            titleAr: "الفريق",
            href: p("/super-agent/agents"),
            icon: "Users",
            description: "Manage your agent team",
            descriptionAr: "إدارة فريق الوكلاء",
            children: [
              {
                title: "Agents",
                titleAr: "الوكلاء",
                href: p("/super-agent/agents"),
                icon: "Star",
                description: "Your assigned agents",
                descriptionAr: "الوكلاء المعينون لك",
              },
              {
                title: "Leads",
                titleAr: "العملاء المحتملون",
                href: p("/super-agent/leads"),
                icon: "Target",
                description: "Lead pipeline & follow-ups",
                descriptionAr: "مسار العملاء والمتابعات",
              },
              {
                title: "Employers",
                titleAr: "أصحاب العمل",
                href: p("/super-agent/employers"),
                icon: "Building2",
                description: "Employers in your region",
                descriptionAr: "أصحاب العمل في منطقتك",
              },
              {
                title: "Referral Links",
                titleAr: "روابط الإحالة",
                href: p("/super-agent/referral-links"),
                icon: "Link2",
                description: "Manage all referral links",
                descriptionAr: "إدارة جميع روابط الإحالة",
              },
              {
                title: "Job Seekers",
                titleAr: "الباحثون عن عمل",
                href: p("/super-agent/job-seekers"),
                icon: "UserSearch",
                description: "Regional candidate directory",
                descriptionAr: "دليل المرشحين الإقليمي",
              },
            ],
          },
          {
            title: "Overview",
            titleAr: "نظرة عامة",
            href: p("/super-agent/placements"),
            icon: "BarChart2",
            description: "Performance & finance",
            descriptionAr: "الأداء والمالية",
            children: [
              {
                title: "Jobs",
                titleAr: "الوظائف",
                href: p("/super-agent/jobs"),
                icon: "Briefcase",
                description: "Regional job listings",
                descriptionAr: "قوائم الوظائف الإقليمية",
              },
              {
                title: "Applications",
                titleAr: "الطلبات",
                href: p("/super-agent/applications"),
                icon: "FileText",
                description: "Team application pipeline",
                descriptionAr: "مسار طلبات الفريق",
              },
              {
                title: "Interviews",
                titleAr: "المقابلات",
                href: p("/super-agent/interviews"),
                icon: "Video",
                description: "Team-wide interview tracking",
                descriptionAr: "تتبع مقابلات الفريق",
              },
              {
                title: "Placements",
                titleAr: "التوظيفات",
                href: p("/super-agent/placements"),
                icon: "UserCheck",
                description: "Confirmed hires & placements",
                descriptionAr: "التعيينات المؤكدة",
              },
              {
                title: "Commissions",
                titleAr: "العمولات",
                href: p("/super-agent/commissions"),
                icon: "DollarSign",
                description: "Team commission tracking",
                descriptionAr: "تتبع عمولات الفريق",
              },
              {
                title: "Invoices",
                titleAr: "الفواتير",
                href: p("/super-agent/invoices"),
                icon: "ReceiptText",
                description: "Team invoice tracking",
                descriptionAr: "تتبع فواتير الفريق",
              },
              {
                title: "Market",
                titleAr: "السوق",
                href: p("/super-agent/market"),
                icon: "TrendingUp",
                description: "Market insights & trends",
                descriptionAr: "رؤى واتجاهات السوق",
              },
              {
                title: "Insights",
                titleAr: "الرؤى",
                href: p("/super-agent/insights"),
                icon: "Lightbulb",
                description: "AI alerts & opportunities",
                descriptionAr: "تنبيهات وفرص مدعومة بالذكاء الاصطناعي",
              },
              {
                title: "Reports",
                titleAr: "التقارير",
                href: p("/super-agent/reports"),
                icon: "BarChart2",
                description: "Performance reports",
                descriptionAr: "تقارير الأداء",
              },
              {
                title: "Targets",
                titleAr: "الأهداف",
                href: p("/super-agent/target-management"),
                icon: "Target",
                description: "Unified target profiles & team tracking",
                descriptionAr: "ملفات الأهداف الموحدة وتتبع الفريق",
              },
              {
                title: "Target Report",
                titleAr: "تقرير الأهداف",
                href: p("/super-agent/target-report"),
                icon: "FileText",
                description: "Team target performance report",
                descriptionAr: "تقرير أداء أهداف الفريق",
              },
              {
                title: "Commission Report",
                titleAr: "تقرير العمولات",
                href: p("/super-agent/commissions-report"),
                icon: "BarChart2",
                description: "Override commissions & team earnings report",
                descriptionAr: "تقرير عمولات التجاوز وأرباح الفريق",
              },
              {
                title: "Territory",
                titleAr: "المنطقة",
                href: p("/super-agent/territory"),
                icon: "MapPin",
                description: "Territory visualization",
                descriptionAr: "عرض المنطقة",
              },
            ],
          },
          {
            title: "Exhibition Requests",
            titleAr: "طلبات المعارض",
            href: p("/super-agent/exhibitions"),
            icon: "CalendarDays",
            description: "Review & approve exhibition requests",
            descriptionAr: "مراجعة واعتماد طلبات المعارض",
          },
          {
            title: "Exhibition Analytics",
            titleAr: "تحليلات المعارض",
            href: p("/super-agent/exhibitions/analytics"),
            icon: "BarChart2",
            description: "Team exhibition performance",
            descriptionAr: "أداء معارض الفريق",
          },
          {
            title: "Resource Downloads",
            titleAr: "تحميل الموارد",
            href: p("/super-agent/resources"),
            icon: "FolderOpen",
            description: "Download exhibition resources",
            descriptionAr: "تحميل موارد المعارض",
          },
          {
            title: "Messages",
            titleAr: "الرسائل",
            href: p("/super-agent/messages"),
            icon: "MessageSquare",
            description: "Messages with agents & employers",
            descriptionAr: "الرسائل مع الوكلاء وأصحاب العمل",
          },
        ],
      },
    ],

    agent: [
      {
        items: [
          {
            title: "Dashboard",
            titleAr: "لوحة التحكم",
            href: p("/agent"),
            icon: "LayoutDashboard",
            description: "Overview & key metrics",
            descriptionAr: "نظرة عامة والمقاييس الرئيسية",
          },
          {
            title: "Hiring",
            titleAr: "التوظيف",
            href: p("/agent/jobs"),
            icon: "Briefcase",
            description: "Manage assigned hiring pipeline",
            descriptionAr: "إدارة مسار التوظيف المخصص",
            children: [
              {
                title: "Jobs",
                titleAr: "الوظائف",
                href: p("/agent/jobs"),
                icon: "Briefcase",
                description: "Manage job postings",
                descriptionAr: "إدارة إعلانات الوظائف",
              },
              {
                title: "Candidates",
                titleAr: "المرشحون",
                href: p("/agent/candidates"),
                icon: "Users",
                description: "Review & manage candidates",
                descriptionAr: "مراجعة وإدارة المرشحين",
              },
              {
                title: "Job Seekers",
                titleAr: "الباحثون عن عمل",
                href: p("/agent/job-seekers"),
                icon: "UserSearch",
                description: "Candidate profiles & matching",
                descriptionAr: "ملفات المرشحين والمطابقة",
              },
              {
                title: "Interviews",
                titleAr: "المقابلات",
                href: p("/agent/interviews"),
                icon: "Calendar",
                description: "Schedule & track interviews",
                descriptionAr: "جدولة وتتبع المقابلات",
              },
              {
                title: "Placements",
                titleAr: "التوظيفات",
                href: p("/agent/placements"),
                icon: "UserCheck",
                description: "Confirmed hires & placements",
                descriptionAr: "التعيينات المؤكدة",
              },
            ],
          },
          {
            title: "Tools",
            titleAr: "الأدوات",
            href: p("/agent/employers"),
            icon: "Wrench",
            description: "Agent tools and account workflow",
            descriptionAr: "أدوات الوكيل وسير عمل الحسابات",
            children: [
              {
                title: "Employers",
                titleAr: "أصحاب العمل",
                href: p("/agent/employers"),
                icon: "Building2",
                description: "Assigned employer accounts",
                descriptionAr: "حسابات أصحاب العمل المعينة",
              },
              {
                title: "Referral Links",
                titleAr: "روابط الإحالة",
                href: p("/agent/referral-links"),
                icon: "Link2",
                description: "Create & manage referral links",
                descriptionAr: "إنشاء وإدارة روابط الإحالة",
              },
              {
                title: "Leads",
                titleAr: "العملاء المحتملون",
                href: p("/agent/leads"),
                icon: "Target",
                description: "Lead pipeline & follow-ups",
                descriptionAr: "مسار العملاء والمتابعات",
              },
              {
                title: "Commissions",
                titleAr: "العمولات",
                href: p("/agent/commissions"),
                icon: "DollarSign",
                description: "Your commission earnings",
                descriptionAr: "أرباح عمولاتك",
              },
              {
                title: "Invoices",
                titleAr: "الفواتير",
                href: p("/agent/invoices"),
                icon: "ReceiptText",
                description: "Create & track invoices",
                descriptionAr: "إنشاء وتتبع الفواتير",
              },
              {
                title: "Reports",
                titleAr: "التقارير",
                href: p("/agent/reports"),
                icon: "BarChart2",
                description: "Activity & performance reports",
                descriptionAr: "تقارير النشاط والأداء",
              },
              {
                title: "Targets",
                titleAr: "الأهداف",
                href: p("/agent/target-management"),
                icon: "Target",
                description: "Dashboard, goals & leaderboard",
                descriptionAr: "لوحة المعلومات والأهداف ولوحة المتصدرين",
              },
              {
                title: "Target Report",
                titleAr: "تقرير الأهداف",
                href: p("/agent/target-report"),
                icon: "FileText",
                description: "Personal target performance report",
                descriptionAr: "تقرير أداء الأهداف الشخصي",
              },
              {
                title: "Commission Report",
                titleAr: "تقرير العمولات",
                href: p("/agent/commissions-report"),
                icon: "BarChart2",
                description: "Personal earnings breakdown & analytics",
                descriptionAr: "تفاصيل أرباحي الشخصية والتحليلات",
              },
              {
                title: "Offers",
                titleAr: "العروض",
                href: p("/agent/offers"),
                icon: "Gift",
                description: "Track candidate offers",
                descriptionAr: "تتبع عروض المرشحين",
              },
              {
                title: "Tasks",
                titleAr: "المهام",
                href: p("/agent/tasks"),
                icon: "CheckSquare",
                description: "Personal to-do & follow-ups",
                descriptionAr: "قائمة المهام والمتابعات",
              },
              {
                title: "Calendar",
                titleAr: "التقويم",
                href: p("/agent/calendar"),
                icon: "CalendarDays",
                description: "Interview & event calendar",
                descriptionAr: "تقويم المقابلات والأحداث",
              },
            ],
          },
          {
            title: "Exhibition Requests",
            titleAr: "طلبات المعارض",
            href: p("/agent/exhibitions"),
            icon: "CalendarDays",
            description: "Submit exhibition participation requests",
            descriptionAr: "تقديم طلبات المشاركة في المعارض",
          },
          {
            title: "Resource Downloads",
            titleAr: "تحميل الموارد",
            href: p("/agent/resources"),
            icon: "FolderOpen",
            description: "Download exhibition resources",
            descriptionAr: "تحميل موارد المعارض",
          },
          {
            title: "Messages",
            titleAr: "الرسائل",
            href: p("/agent/messages"),
            icon: "MessageSquare",
            description: "Messages with employers & super agents",
            descriptionAr: "الرسائل مع أصحاب العمل والوكلاء الكبار",
          },
          {
            title: "Team Chat",
            titleAr: "دردشة الفريق",
            href: p("/agent/chat"),
            icon: "Hash",
            description: "Team channels & discussions",
            descriptionAr: "قنوات الفريق والمناقشات",
          },
        ],
      },
    ],

    employer: [
      {
        items: [
          {
            title: "Dashboard",
            titleAr: "لوحة التحكم",
            href: p("/employer"),
            icon: "LayoutDashboard",
            description: "Overview & key metrics",
            descriptionAr: "نظرة عامة والمقاييس الرئيسية",
          },
          // Daily-drivers are top-level — one click, no flyout. The "Hiring"
          // group keeps only the less-frequent pipeline pages.
          {
            title: "Jobs",
            titleAr: "الوظائف",
            href: p("/employer/jobs"),
            icon: "Briefcase",
            description: "Post & manage job listings",
            descriptionAr: "نشر وإدارة الوظائف",
          },
          {
            title: "Applications",
            titleAr: "الطلبات",
            href: p("/employer/applications"),
            icon: "FileText",
            description: "Review candidate applications",
            descriptionAr: "مراجعة طلبات المرشحين",
          },
          {
            title: "Interviews",
            titleAr: "المقابلات",
            href: p("/employer/interviews"),
            icon: "Calendar",
            description: "Schedule & track interviews",
            descriptionAr: "جدولة وتتبع المقابلات",
          },
          {
            title: "Candidates",
            titleAr: "المرشحون",
            href: p("/employer/candidates"),
            icon: "UserSearch",
            description: "Browse candidates & talent pools",
            descriptionAr: "تصفح المرشحين ومجموعات المواهب",
            children: [
              {
                title: "All Candidates",
                titleAr: "كل المرشحين",
                href: p("/employer/candidates"),
                icon: "UserSearch",
                description: "Browse & search candidates",
                descriptionAr: "تصفح والبحث عن المرشحين",
              },
              {
                title: "Talent Pools",
                titleAr: "مجموعات المواهب",
                href: p("/employer/talent-pools"),
                icon: "Layers",
                description: "Saved candidate pools for future roles",
                descriptionAr: "مجموعات المرشحين المحفوظة للوظائف المستقبلية",
              },
            ],
          },
          {
            title: "Hiring",
            titleAr: "التوظيف",
            href: p("/employer/offers"),
            icon: "UserCheck",
            description: "Offers, placements & background checks",
            descriptionAr: "العروض والتوظيفات والتحقق من الخلفية",
            children: [
              {
                title: "Offers",
                titleAr: "العروض",
                href: p("/employer/offers"),
                icon: "DollarSign",
                description: "Track sent offers",
                descriptionAr: "تتبع العروض المرسلة",
              },
              {
                title: "Placements",
                titleAr: "التوظيفات",
                href: p("/employer/placements"),
                icon: "UserCheck",
                description: "Confirmed hires & placements",
                descriptionAr: "التعيينات المؤكدة",
              },
              {
                title: "Background Checks",
                titleAr: "التحقق من الخلفية",
                href: p("/employer/background-checks"),
                icon: "ShieldCheck",
                description: "Reference & background checks",
                descriptionAr: "التحقق من المراجع والخلفية",
              },
            ],
          },
          {
            title: "Tools",
            titleAr: "الأدوات",
            href: p("/employer/workflow"),
            icon: "Wrench",
            description: "Hiring tools & automation",
            descriptionAr: "أدوات التوظيف والأتمتة",
            children: [
              {
                title: "Hiring Workflows",
                titleAr: "مسارات التوظيف",
                href: p("/employer/workflow"),
                icon: "GitBranch",
                description: "Default pipeline for new jobs (override per job)",
                descriptionAr: "المسار الافتراضي للوظائف الجديدة (يمكن تخصيصه لكل وظيفة)",
              },
              {
                title: "AI Matching Preferences",
                titleAr: "تفضيلات المطابقة الذكية",
                href: p("/employer/matching-weights"),
                icon: "SlidersHorizontal",
                description: "How AI weighs skills, experience & fit (override per job)",
                descriptionAr: "كيف يوازن الذكاء الاصطناعي المهارات والخبرة (يمكن تخصيصها لكل وظيفة)",
              },
              {
                title: "Communication Templates",
                titleAr: "قوالب الاتصالات",
                href: p("/employer/comm-templates"),
                icon: "MessageSquare",
                description: "Email templates for candidates",
                descriptionAr: "قوالب البريد الإلكتروني للمرشحين",
              },
              {
                title: "Email Sequences",
                titleAr: "تسلسلات البريد الإلكتروني",
                href: p("/employer/campaigns"),
                icon: "Mail",
                description: "Automated email nurture sequences",
                descriptionAr: "تسلسلات بريد إلكتروني تلقائية للرعاية",
              },
              {
                title: "Job Templates",
                titleAr: "قوالب الوظائف",
                href: p("/employer/job-templates"),
                icon: "FileText",
                description: "Reusable job posting templates",
                descriptionAr: "قوالب نشر الوظائف القابلة لإعادة الاستخدام",
              },
            ],
          },
          {
            // ponytail: single-item "Marketing" group flattened to a direct link
            title: "Job Posters",
            titleAr: "ملصقات الوظائف",
            href: p("/employer/my-posters"),
            icon: "Image",
            description: "AI-generated recruitment posters",
            descriptionAr: "ملصقات التوظيف المولدة بالذكاء الاصطناعي",
          },
          {
            title: "Calendar",
            titleAr: "التقويم",
            href: p("/employer/calendar"),
            icon: "CalendarDays",
            description: "Interview calendar view",
            descriptionAr: "عرض تقويم المقابلات",
          },
          {
            title: "Analytics",
            titleAr: "التحليلات",
            href: p("/employer/analytics"),
            icon: "BarChart2",
            description: "Pipeline analytics & insights",
            descriptionAr: "تحليلات خط التوظيف والرؤى",
          },
          {
            title: "Messages",
            titleAr: "الرسائل",
            href: p("/employer/messages"),
            icon: "MessageSquare",
            description: "Direct messages with candidates",
            descriptionAr: "الرسائل المباشرة مع المرشحين",
          },
          // ponytail: "Notifications" nav item removed — the topbar bell is the
          // single entry point; duplicating it in the sidebar just added noise.
          {
            // ponytail: "Team Members" invite child removed — feature disabled,
            // see EMPLOYER-FIX-PLAN E6. Group renamed "Activity" since it only
            // holds logs; restore "Team" name when member management ships.
            title: "Activity",
            titleAr: "النشاط",
            href: p("/employer/team/activity-logs"),
            icon: "Activity",
            description: "Team activity & history",
            descriptionAr: "نشاط الفريق وسجله",
            children: [
              {
                title: "Activity Logs",
                titleAr: "سجل النشاط",
                href: p("/employer/team/activity-logs"),
                icon: "Activity",
                description: "View all team member activities",
                descriptionAr: "عرض جميع أنشطة أعضاء الفريق",
              },
              {
                title: "Agent History",
                titleAr: "سجل الوكيل",
                href: p("/employer/activity-history"),
                icon: "History",
                description: "Actions by agents & admins on your behalf",
                descriptionAr: "الإجراءات من الوكلاء والمسؤولين نيابة عنك",
              },
            ],
          },
          {
            title: "Company Settings",
            titleAr: "إعدادات الشركة",
            href: p("/employer/settings"),
            icon: "Settings",
            description: "Company profile & verification",
            descriptionAr: "الملف الشخصي للشركة والتحقق",
            children: [
              {
                title: "Profile & Verification",
                titleAr: "الملف والتحقق",
                href: p("/employer/settings"),
                icon: "Settings",
                description: "Company profile & verification",
                descriptionAr: "الملف الشخصي للشركة والتحقق",
              },
              {
                title: "Subscription",
                titleAr: "الاشتراك",
                href: p("/employer/subscription"),
                icon: "Crown",
                description: "View plan, usage & limits",
                descriptionAr: "عرض الخطة والاستخدام والحدود",
              },
              {
                title: "Invoices & Billing",
                titleAr: "الفواتير والفوترة",
                href: p("/employer/invoices"),
                icon: "FileText",
                description: "View invoices and payment history",
                descriptionAr: "عرض الفواتير وسجل الدفعات",
              },
              {
                title: "Payment Setup",
                titleAr: "إعداد الدفع",
                href: p("/employer/payment-setup"),
                icon: "CreditCard",
                description: "Configure payment gateway",
                descriptionAr: "إعداد بوابة الدفع",
              },
            ],
          },
        ],
      },
    ],

    job_seeker: [
      {
        items: [
          {
            title: "Home",
            titleAr: "لوحة التحكم",
            href: p("/job-seeker"),
            icon: "LayoutDashboard",
            description: "Your job seeker home",
            descriptionAr: "نظرة عامة والمقاييس الرئيسية",
          },
          {
            title: "My Career",
            titleAr: "مسيرتي المهنية",
            href: p("/job-seeker/profile"),
            icon: "UserCircle",
            description: "Profile & career tools",
            descriptionAr: "الملف الشخصي وأدوات المهنة",
            children: [
              {
                title: "Profile",
                titleAr: "الملف الشخصي",
                href: p("/job-seeker/profile"),
                icon: "UserCircle",
                description: "Edit your profile",
                descriptionAr: "تعديل ملفك الشخصي",
              },
              {
                title: "Personal Details",
                titleAr: "البيانات الشخصية",
                href: p("/job-seeker/profile/personal-details"),
                icon: "UserCircle",
                description: "Gender, DOB, address & languages",
                descriptionAr: "الجنس، تاريخ الميلاد، العنوان واللغات",
              },
              {
                title: "Job Preferences",
                titleAr: "تفضيلات الوظيفة",
                href: p("/job-seeker/preferences"),
                icon: "Target",
                description: "Set your job matching preferences",
                descriptionAr: "تعيين تفضيلات مطابقة الوظائف",
              },
              {
                title: "Jobs",
                titleAr: "البحث عن وظيفة",
                href: p("/job-seeker/jobs"),
                icon: "Briefcase",
                description: "Browse recommended jobs",
                descriptionAr: "تصفح الوظائف المتاحة",
              },
              {
                title: "Search",
                titleAr: "البحث",
                href: p("/job-seeker/search"),
                icon: "Search",
                description: "Search jobs, companies & more",
                descriptionAr: "البحث عن الوظائف والشركات والمزيد",
              },
              {
                title: "Applications",
                titleAr: "طلباتي",
                href: p("/job-seeker/applications"),
                icon: "FileText",
                description: "Track your applications",
                descriptionAr: "تتبع طلباتك",
              },
              {
                title: "Interviews",
                titleAr: "مقابلاتي",
                href: p("/job-seeker/interviews"),
                icon: "Calendar",
                description: "Upcoming interview schedule",
                descriptionAr: "جدول المقابلات القادمة",
              },
              {
                title: "Saved Jobs",
                titleAr: "الوظائف المحفوظة",
                href: p("/job-seeker/saved-jobs"),
                icon: "Heart",
                description: "Your saved jobs",
                descriptionAr: "وظائفك المحفوظة",
              },
              {
                title: "Offers",
                titleAr: "العروض",
                href: p("/job-seeker/offers"),
                icon: "DollarSign",
                description: "Review received offers",
                descriptionAr: "مراجعة العروض المستلمة",
              },
              {
                title: "CV Builder",
                titleAr: "بناء السيرة الذاتية",
                href: p("/job-seeker/cv"),
                icon: "FileText",
                description: "Build & download your professional CV",
                descriptionAr: "بناء وتحميل سيرتك الذاتية المهنية",
              },
              {
                title: "Skills",
                titleAr: "المهارات",
                href: p("/job-seeker/skills"),
                icon: "Wrench",
                description: "Manage your skills",
                descriptionAr: "إدارة مهاراتك",
              },
              {
                title: "Documents",
                titleAr: "المستندات",
                href: p("/job-seeker/documents"),
                icon: "FolderOpen",
                description: "Upload certificates & docs",
                descriptionAr: "رفع الشهادات والمستندات",
              },
              {
                title: "Courses",
                titleAr: "الدورات",
                href: p("/job-seeker/courses"),
                icon: "BookOpen",
                description: "Learning & certification",
                descriptionAr: "التعلم والشهادات",
              },
              {
                title: "Companies",
                titleAr: "الشركات",
                href: p("/job-seeker/companies"),
                icon: "Building2",
                description: "Explore employers on the platform",
                descriptionAr: "استكشف أصحاب العمل على المنصة",
              },
              {
                title: "Portfolio",
                titleAr: "الأعمال",
                href: p("/job-seeker/portfolio"),
                icon: "FolderOpen",
                description: "Showcase your projects & work",
                descriptionAr: "اعرض مشاريعك وأعمالك",
              },
              {
                title: "Profile Views",
                titleAr: "من شاهد ملفك",
                href: p("/job-seeker/profile-views"),
                icon: "Eye",
                description: "See who viewed your profile",
                descriptionAr: "عرض من شاهد ملفك الشخصي",
              },
              {
                title: "Profile Boost",
                titleAr: "تعزيز الملف الشخصي",
                href: p("/job-seeker/profile-boost"),
                icon: "TrendingUp",
                description: "Get your profile noticed by more recruiters",
                descriptionAr: "اجعل ملفك الشخصي أكثر ظهورًا للمسؤولين عن التوظيف",
              },
            ],
          },
          {
            title: "Calendar",
            titleAr: "التقويم",
            href: p("/job-seeker/calendar"),
            icon: "CalendarDays",
            description: "Interview calendar view",
            descriptionAr: "عرض تقويم المقابلات",
          },
          {
            title: "Saved Searches",
            titleAr: "البحث المحفوظ",
            href: p("/job-seeker/saved-searches"),
            icon: "Bell",
            description: "Search alerts & saved queries",
            descriptionAr: "تنبيهات البحث والاستعلامات المحفوظة",
          },
          {
            title: "Referral Program",
            titleAr: "برنامج الإحالة",
            href: p("/job-seeker/referral"),
            icon: "Gift",
            description: "Invite friends & earn rewards",
            descriptionAr: "ادعُ أصدقاءك واكسب مكافآت",
          },
          {
            title: "Support",
            titleAr: "الدعم",
            href: p("/job-seeker/messages"),
            icon: "Headset",
            description: "Contact support for help",
            descriptionAr: "تواصل مع الدعم للمساعدة",
          },
          {
            title: "Settings",
            titleAr: "الإعدادات",
            href: p("/job-seeker/settings"),
            icon: "Settings",
            description: "Account preferences",
            descriptionAr: "تفضيلات الحساب",
          },
          {
            title: "My Subscription",
            titleAr: "اشتراكي",
            href: p("/job-seeker/subscription"),
            icon: "Crown",
            description: "View plan, usage & invoices",
            descriptionAr: "عرض الخطة والاستخدام والفواتير",
          },
        ],
      },
    ],
  };
}

export function getNavGroups(role: UserRole, locale = "en"): NavGroup[] {
  return buildNav(locale)[role] ?? [];
}

/** Flat items for CommandMenu */
export function getAllNavItems(role: UserRole, locale = "en"): NavItem[] {
  const groups = getNavGroups(role, locale);
  return groups.flatMap((g) =>
    g.items.flatMap((item) => [item, ...(item.children ?? [])])
  );
}
