import type { UserRole } from "@/models/User";
import type { IconName } from "./iconRegistry";

/** Resources in the system */
export type Resource = string;

export interface NavItem {
  title: string;
  titleAr: string;
  href: string;
  /** Plain icon name — resolved to a Lucide component inside Client Components via getIcon() */
  icon: IconName;
  badge?: string;
  /** Short description shown in command menu */
  description?: string;
  descriptionAr?: string;
  children?: NavItem[];
}

export interface NavGroup {
  label?: string;
  labelAr?: string;
  items: NavItem[];
}

function buildNav(locale: string): Record<UserRole, NavGroup[]> {
  const p = (path: string) => `/${locale}${path}`;

  return {
    admin: [
      {
        items: [
          {
            title: "Dashboard",
            titleAr: "لوحة التحكم",
            href: p("/admin"),
            icon: "LayoutDashboard",
            description: "Overview & key metrics",
            descriptionAr: "نظرة عامة والمقاييس الرئيسية",
          },
          {
            title: "Recruitment",
            titleAr: "التوظيف",
            href: p("/admin/jobs"),
            icon: "Briefcase",
            description: "Manage the hiring pipeline",
            descriptionAr: "إدارة عملية التوظيف",
            children: [
              {
                title: "Jobs",
                titleAr: "الوظائف",
                href: p("/admin/jobs"),
                icon: "Briefcase",
                description: "Manage job listings",
                descriptionAr: "إدارة الوظائف المنشورة",
              },
              {
                title: "Applications",
                titleAr: "الطلبات",
                href: p("/admin/applications"),
                icon: "FileText",
                description: "Review candidate applications",
                descriptionAr: "مراجعة طلبات المرشحين",
              },
              {
                title: "Interviews",
                titleAr: "المقابلات",
                href: p("/admin/interviews"),
                icon: "Calendar",
                description: "Schedule & track interviews",
                descriptionAr: "جدولة وتتبع المقابلات",
              },
              {
                title: "Placements",
                titleAr: "التوظيفات",
                href: p("/admin/placements"),
                icon: "UserCheck",
                description: "Confirmed hires & placements",
                descriptionAr: "التعيينات المؤكدة",
              },
              {
                title: "Approvals",
                titleAr: "الموافقات",
                href: p("/admin/approvals"),
                icon: "CheckCircle",
                description: "Pending approval requests",
                descriptionAr: "طلبات الموافقة المعلقة",
              },
            ],
          },
          {
            title: "People",
            titleAr: "الأشخاص",
            href: p("/admin/employers"),
            icon: "Users",
            description: "Manage all users & accounts",
            descriptionAr: "إدارة جميع المستخدمين والحسابات",
            children: [
              {
                title: "Employers",
                titleAr: "أصحاب العمل",
                href: p("/admin/employers"),
                icon: "Building2",
                description: "Company accounts & profiles",
                descriptionAr: "حسابات وملفات الشركات",
              },
              {
                title: "Job Seekers",
                titleAr: "الباحثون عن عمل",
                href: p("/admin/job-seekers"),
                icon: "UserSearch",
                description: "Candidate profiles & CVs",
                descriptionAr: "ملفات المرشحين والسير الذاتية",
              },
              {
                title: "Agents",
                titleAr: "الوكلاء",
                href: p("/admin/agents"),
                icon: "Star",
                description: "Recruitment agents & regions",
                descriptionAr: "وكلاء التوظيف والمناطق",
              },
              {
                title: "Super Agents",
                titleAr: "الوكلاء الكبار",
                href: p("/admin/super-agents"),
                icon: "Shield",
                description: "Agent managers & team leads",
                descriptionAr: "مديرو الوكلاء وقادة الفرق",
              },
              {
                title: "Users",
                titleAr: "المستخدمون",
                href: p("/admin/users"),
                icon: "UserCog",
                description: "System users & permissions",
                descriptionAr: "مستخدمو النظام والأذونات",
              },
            ],
          },
          {
            title: "Finance",
            titleAr: "المالية",
            href: p("/admin/commissions"),
            icon: "DollarSign",
            description: "Commissions & payments",
            descriptionAr: "العمولات والمدفوعات",
            children: [
              {
                title: "Commissions",
                titleAr: "العمولات",
                href: p("/admin/commissions"),
                icon: "DollarSign",
                description: "Track & manage commissions",
                descriptionAr: "تتبع وإدارة العمولات",
              },
            ],
          },
          {
            title: "CMS / Landing Page",
            titleAr: "نظام إدارة المحتوى",
            href: p("/admin/cms"),
            icon: "PanelsTopLeft",
            description: "Manage website content",
            descriptionAr: "إدارة محتوى الموقع",
            children: [
              {
                title: "CMS Overview",
                titleAr: "نظرة عامة",
                href: p("/admin/cms"),
                icon: "PanelsTopLeft",
                description: "Content management dashboard",
                descriptionAr: "لوحة إدارة المحتوى",
              },
              {
                title: "FAQs",
                titleAr: "الأسئلة الشائعة",
                href: p("/admin/cms/faqs"),
                icon: "HelpCircle",
                description: "Frequently asked questions",
                descriptionAr: "الأسئلة المتداولة",
              },
              {
                title: "Blog Posts",
                titleAr: "المقالات",
                href: p("/admin/cms/blogs"),
                icon: "Newspaper",
                description: "Articles & news posts",
                descriptionAr: "المقالات والأخبار",
              },
              {
                title: "Testimonials",
                titleAr: "شهادات العملاء",
                href: p("/admin/cms/testimonials"),
                icon: "Quote",
                description: "Client success stories",
                descriptionAr: "قصص نجاح العملاء",
              },
              {
                title: "Banners",
                titleAr: "البانرات",
                href: p("/admin/cms/banners"),
                icon: "Image",
                description: "Homepage & promo banners",
                descriptionAr: "بانرات الصفحة الرئيسية",
              },
              {
                title: "Videos",
                titleAr: "الفيديوهات",
                href: p("/admin/cms/videos"),
                icon: "Video",
                description: "Video content library",
                descriptionAr: "مكتبة محتوى الفيديو",
              },
              {
                title: "Static Pages",
                titleAr: "الصفحات الثابتة",
                href: p("/admin/cms/static-pages"),
                icon: "FileText",
                description: "Privacy, terms & custom pages",
                descriptionAr: "الخصوصية والشروط والصفحات المخصصة",
              },
              {
                title: "Contact Inbox",
                titleAr: "صندوق الرسائل",
                href: p("/admin/cms/contact-submissions"),
                icon: "Mail",
                description: "Contact form submissions",
                descriptionAr: "رسائل نموذج الاتصال",
              },
            ],
          },
          {
            title: "Job Attributes",
            titleAr: "سمات الوظيفة",
            href: p("/admin/job-attributes"),
            icon: "SlidersHorizontal",
            description: "Configure job metadata",
            descriptionAr: "إعداد بيانات الوظائف",
            children: [
              {
                title: "Salary Periods",
                titleAr: "فترات الراتب",
                href: p("/admin/job-attributes/salary-periods"),
                icon: "Clock",
                description: "Monthly, yearly, hourly, etc.",
                descriptionAr: "شهري، سنوي، بالساعة، إلخ",
              },
              {
                title: "Ownership Types",
                titleAr: "أنواع الملكية",
                href: p("/admin/job-attributes/ownership-types"),
                icon: "Building",
                description: "Company ownership categories",
                descriptionAr: "فئات ملكية الشركات",
              },
              {
                title: "Marital Status",
                titleAr: "الحالة الاجتماعية",
                href: p("/admin/job-attributes/marital-statuses"),
                icon: "Heart",
                description: "Marital status options",
                descriptionAr: "خيارات الحالة الاجتماعية",
              },
              {
                title: "Result Types",
                titleAr: "أنواع النتائج",
                href: p("/admin/job-attributes/result-types"),
                icon: "Award",
                description: "Academic result categories",
                descriptionAr: "فئات النتائج الأكاديمية",
              },
              {
                title: "Major Subjects",
                titleAr: "التخصصات الرئيسية",
                href: p("/admin/job-attributes/major-subjects"),
                icon: "GraduationCap",
                description: "Fields of study",
                descriptionAr: "مجالات الدراسة",
              },
              {
                title: "Degree Types",
                titleAr: "أنواع الشهادات",
                href: p("/admin/job-attributes/degree-types"),
                icon: "ScrollText",
                description: "BSc, MSc, PhD, etc.",
                descriptionAr: "بكالوريوس، ماجستير، دكتوراه، إلخ",
              },
              {
                title: "Degree Levels",
                titleAr: "مستويات الشهادات",
                href: p("/admin/job-attributes/degree-levels"),
                icon: "BarChart2",
                description: "Education level hierarchy",
                descriptionAr: "تسلسل مستويات التعليم",
              },
              {
                title: "Job Shifts",
                titleAr: "نوبات العمل",
                href: p("/admin/job-attributes/job-shifts"),
                icon: "Sun",
                description: "Day, night, rotating shifts",
                descriptionAr: "نوبات صباحية، مسائية، متناوبة",
              },
              {
                title: "Job Types",
                titleAr: "أنواع الوظائف",
                href: p("/admin/job-attributes/job-types"),
                icon: "Layers",
                description: "Full-time, part-time, contract",
                descriptionAr: "دوام كامل، جزئي، عقد",
              },
              {
                title: "Job Skills",
                titleAr: "المهارات الوظيفية",
                href: p("/admin/job-attributes/job-skills"),
                icon: "Wrench",
                description: "Skills & competency tags",
                descriptionAr: "علامات المهارات والكفاءات",
              },
              {
                title: "Job Experience",
                titleAr: "الخبرة الوظيفية",
                href: p("/admin/job-attributes/job-experience"),
                icon: "TrendingUp",
                description: "Experience level ranges",
                descriptionAr: "نطاقات مستوى الخبرة",
              },
              {
                title: "Industries",
                titleAr: "الصناعات",
                href: p("/admin/job-attributes/industries"),
                icon: "Factory",
                description: "Industry sector list",
                descriptionAr: "قائمة القطاعات الصناعية",
              },
              {
                title: "Genders",
                titleAr: "الجنس",
                href: p("/admin/job-attributes/genders"),
                icon: "UserCircle",
                description: "Gender preference options",
                descriptionAr: "خيارات تفضيل الجنس",
              },
              {
                title: "Functional Areas",
                titleAr: "المجالات الوظيفية",
                href: p("/admin/job-attributes/functional-areas"),
                icon: "Grid3x3",
                description: "Job function categories",
                descriptionAr: "فئات الوظائف",
              },
              {
                title: "Career Levels",
                titleAr: "المستويات المهنية",
                href: p("/admin/job-attributes/career-levels"),
                icon: "Milestone",
                description: "Entry, mid, senior levels",
                descriptionAr: "مستويات مبتدئ، متوسط، أقدم",
              },
              {
                title: "Language Levels",
                titleAr: "مستويات اللغة",
                href: p("/admin/job-attributes/language-levels"),
                icon: "Languages",
                description: "Language proficiency scale",
                descriptionAr: "مقياس إتقان اللغة",
              },
            ],
          },
          {
            title: "Location Data",
            titleAr: "بيانات الموقع",
            href: p("/admin/location-data"),
            icon: "Globe",
            description: "Countries, states & cities",
            descriptionAr: "الدول والمحافظات والمدن",
            children: [
              {
                title: "Countries",
                titleAr: "الدول",
                href: p("/admin/location-data/countries"),
                icon: "Globe",
                description: "Manage country list",
                descriptionAr: "إدارة قائمة الدول",
              },
              {
                title: "States",
                titleAr: "المحافظات",
                href: p("/admin/location-data/states"),
                icon: "Map",
                description: "States & provinces",
                descriptionAr: "المحافظات والأقاليم",
              },
              {
                title: "Cities",
                titleAr: "المدن",
                href: p("/admin/location-data/cities"),
                icon: "MapPin",
                description: "City directory",
                descriptionAr: "دليل المدن",
              },
            ],
          },
          {
            title: "System",
            titleAr: "النظام",
            href: p("/admin/reports"),
            icon: "Settings",
            description: "Reports, logs & settings",
            descriptionAr: "التقارير والسجلات والإعدادات",
            children: [
              {
                title: "Reports",
                titleAr: "التقارير",
                href: p("/admin/reports"),
                icon: "BarChart2",
                description: "Analytics & reports",
                descriptionAr: "التحليلات والتقارير",
              },
              {
                title: "Analytics",
                titleAr: "التحليلات",
                href: p("/admin/analytics"),
                icon: "TrendingUp",
                description: "Platform usage analytics",
                descriptionAr: "تحليلات استخدام المنصة",
              },
              {
                title: "Audit Logs",
                titleAr: "سجلات التدقيق",
                href: p("/admin/audit-logs"),
                icon: "ClipboardList",
                description: "Track all system activity",
                descriptionAr: "تتبع جميع أنشطة النظام",
              },
              {
                title: "Communications",
                titleAr: "الاتصالات",
                href: p("/admin/communications"),
                icon: "MessageSquare",
                description: "Email & notification logs",
                descriptionAr: "سجلات البريد والإشعارات",
              },
              {
                title: "Task Board",
                titleAr: "لوحة المهام",
                href: p("/admin/tasks"),
                icon: "ClipboardList",
                description: "Internal task management",
                descriptionAr: "إدارة المهام الداخلية",
              },
              {
                title: "Design System",
                titleAr: "نظام التصميم",
                href: p("/admin/design-system"),
                icon: "Palette",
                description: "UI component reference",
                descriptionAr: "مرجع مكونات واجهة المستخدم",
              },
              {
                title: "Settings",
                titleAr: "الإعدادات",
                href: p("/admin/settings"),
                icon: "Settings",
                description: "Platform configuration",
                descriptionAr: "إعدادات المنصة",
              },
              {
                title: "Notification System",
                titleAr: "نظام الإشعارات",
                href: p("/admin/settings/notifications"),
                icon: "Bell",
                description: "Email automation & monitoring",
                descriptionAr: "أتمتة البريد الإلكتروني والمراقبة",
              },
            ],
          },
          {
            title: "Messages",
            titleAr: "الرسائل",
            href: p("/admin/messages"),
            icon: "MessageSquare",
            description: "Messages & support tickets",
            descriptionAr: "الرسائل وتذاكر الدعم",
          },
          {
            title: "Notifications",
            titleAr: "الإشعارات",
            href: p("/notifications"),
            icon: "Bell",
            description: "View all notifications",
            descriptionAr: "عرض جميع الإشعارات",
          },
        ],
      },
    ],

    super_agent: [
      {
        items: [
          {
            title: "Dashboard",
            titleAr: "لوحة التحكم",
            href: p("/super-agent"),
            icon: "LayoutDashboard",
            description: "Overview & key metrics",
            descriptionAr: "نظرة عامة والمقاييس الرئيسية",
          },
          {
            title: "Team",
            titleAr: "الفريق",
            href: p("/super-agent/agents"),
            icon: "Users",
            description: "Manage your agent team",
            descriptionAr: "إدارة فريق الوكلاء",
            children: [
              {
                title: "Agents",
                titleAr: "الوكلاء",
                href: p("/super-agent/agents"),
                icon: "Star",
                description: "Your assigned agents",
                descriptionAr: "الوكلاء المعينون لك",
              },
              {
                title: "Leads",
                titleAr: "العملاء المحتملون",
                href: p("/super-agent/leads"),
                icon: "Target",
                description: "Lead pipeline & follow-ups",
                descriptionAr: "مسار العملاء والمتابعات",
              },
              {
                title: "Employers",
                titleAr: "أصحاب العمل",
                href: p("/super-agent/employers"),
                icon: "Building2",
                description: "Employers in your region",
                descriptionAr: "أصحاب العمل في منطقتك",
              },
            ],
          },
          {
            title: "Overview",
            titleAr: "نظرة عامة",
            href: p("/super-agent/placements"),
            icon: "BarChart2",
            description: "Performance & finance",
            descriptionAr: "الأداء والمالية",
            children: [
              {
                title: "Jobs",
                titleAr: "الوظائف",
                href: p("/super-agent/approvals"),
                icon: "Briefcase",
                description: "Regional job listings",
                descriptionAr: "قوائم الوظائف الإقليمية",
              },
              {
                title: "Placements",
                titleAr: "التوظيفات",
                href: p("/super-agent/placements"),
                icon: "UserCheck",
                description: "Confirmed hires & placements",
                descriptionAr: "التعيينات المؤكدة",
              },
              {
                title: "Commissions",
                titleAr: "العمولات",
                href: p("/super-agent/commissions"),
                icon: "DollarSign",
                description: "Team commission tracking",
                descriptionAr: "تتبع عمولات الفريق",
              },
              {
                title: "Market",
                titleAr: "السوق",
                href: p("/super-agent/market"),
                icon: "TrendingUp",
                description: "Market insights & trends",
                descriptionAr: "رؤى واتجاهات السوق",
              },
              {
                title: "Reports",
                titleAr: "التقارير",
                href: p("/super-agent/reports"),
                icon: "BarChart2",
                description: "Performance reports",
                descriptionAr: "تقارير الأداء",
              },
            ],
          },
          {
            title: "Messages",
            titleAr: "الرسائل",
            href: p("/super-agent/messages"),
            icon: "MessageSquare",
            description: "Messages with agents & employers",
            descriptionAr: "الرسائل مع الوكلاء وأصحاب العمل",
          },
          {
            title: "Settings",
            titleAr: "الإعدادات",
            href: p("/super-agent/settings"),
            icon: "Settings",
            description: "Region & currency preferences",
            descriptionAr: "تفضيلات المنطقة والعملة",
          },
          {
            title: "Notifications",
            titleAr: "الإشعارات",
            href: p("/notifications"),
            icon: "Bell",
            description: "View all notifications",
            descriptionAr: "عرض جميع الإشعارات",
          },
        ],
      },
    ],

    agent: [
      {
        items: [
          {
            title: "Dashboard",
            titleAr: "لوحة التحكم",
            href: p("/agent"),
            icon: "LayoutDashboard",
            description: "Overview & key metrics",
            descriptionAr: "نظرة عامة والمقاييس الرئيسية",
          },
          {
            title: "Hiring",
            titleAr: "التوظيف",
            href: p("/agent/jobs"),
            icon: "Briefcase",
            description: "Manage assigned hiring pipeline",
            descriptionAr: "إدارة مسار التوظيف المخصص",
            children: [
              {
                title: "Jobs",
                titleAr: "الوظائف",
                href: p("/agent/jobs"),
                icon: "Briefcase",
                description: "Manage job postings",
                descriptionAr: "إدارة إعلانات الوظائف",
              },
              {
                title: "Candidates",
                titleAr: "المرشحون",
                href: p("/agent/candidates"),
                icon: "Users",
                description: "Review & manage candidates",
                descriptionAr: "مراجعة وإدارة المرشحين",
              },
              {
                title: "Job Seekers",
                titleAr: "الباحثون عن عمل",
                href: p("/agent/job-seekers"),
                icon: "UserSearch",
                description: "Candidate profiles & matching",
                descriptionAr: "ملفات المرشحين والمطابقة",
              },
              {
                title: "Interviews",
                titleAr: "المقابلات",
                href: p("/agent/interviews"),
                icon: "Calendar",
                description: "Schedule & track interviews",
                descriptionAr: "جدولة وتتبع المقابلات",
              },
              {
                title: "Placements",
                titleAr: "التوظيفات",
                href: p("/agent/placements"),
                icon: "UserCheck",
                description: "Confirmed hires & placements",
                descriptionAr: "التعيينات المؤكدة",
              },
            ],
          },
          {
            title: "Tools",
            titleAr: "الأدوات",
            href: p("/agent/employers"),
            icon: "Wrench",
            description: "Agent tools and account workflow",
            descriptionAr: "أدوات الوكيل وسير عمل الحسابات",
            children: [
              {
                title: "Employers",
                titleAr: "أصحاب العمل",
                href: p("/agent/employers"),
                icon: "Building2",
                description: "Assigned employer accounts",
                descriptionAr: "حسابات أصحاب العمل المعينة",
              },
              {
                title: "Leads",
                titleAr: "العملاء المحتملون",
                href: p("/agent/leads"),
                icon: "Target",
                description: "Lead pipeline & follow-ups",
                descriptionAr: "مسار العملاء والمتابعات",
              },
              {
                title: "Commissions",
                titleAr: "العمولات",
                href: p("/agent/commissions"),
                icon: "DollarSign",
                description: "Your commission earnings",
                descriptionAr: "أرباح عمولاتك",
              },
              {
                title: "Reports",
                titleAr: "التقارير",
                href: p("/agent/reports"),
                icon: "BarChart2",
                description: "Activity & performance reports",
                descriptionAr: "تقارير النشاط والأداء",
              },
            ],
          },
          {
            title: "Messages",
            titleAr: "الرسائل",
            href: p("/agent/messages"),
            icon: "MessageSquare",
            description: "Messages with employers & super agents",
            descriptionAr: "الرسائل مع أصحاب العمل والوكلاء الكبار",
          },
          {
            title: "Settings",
            titleAr: "الإعدادات",
            href: p("/agent/settings"),
            icon: "Settings",
            description: "Region & currency preferences",
            descriptionAr: "تفضيلات المنطقة والعملة",
          },
          {
            title: "Notifications",
            titleAr: "الإشعارات",
            href: p("/notifications"),
            icon: "Bell",
            description: "View all notifications",
            descriptionAr: "عرض جميع الإشعارات",
          },
        ],
      },
    ],

    employer: [
      {
        items: [
          {
            title: "Dashboard",
            titleAr: "لوحة التحكم",
            href: p("/employer"),
            icon: "LayoutDashboard",
            description: "Overview & key metrics",
            descriptionAr: "نظرة عامة والمقاييس الرئيسية",
          },
          {
            title: "Hiring",
            titleAr: "التوظيف",
            href: p("/employer/jobs"),
            icon: "Briefcase",
            description: "Manage hiring pipeline",
            descriptionAr: "إدارة عملية التوظيف",
            children: [
              {
                title: "Jobs",
                titleAr: "الوظائف",
                href: p("/employer/jobs"),
                icon: "Briefcase",
                description: "Post & manage job listings",
                descriptionAr: "نشر وإدارة الوظائف",
              },
              {
                title: "Candidates",
                titleAr: "المرشحون",
                href: p("/employer/candidates"),
                icon: "UserSearch",
                description: "Browse & search candidates",
                descriptionAr: "تصفح والبحث عن المرشحين",
              },
              {
                title: "Interviews",
                titleAr: "المقابلات",
                href: p("/employer/interviews"),
                icon: "Calendar",
                description: "Schedule & track interviews",
                descriptionAr: "جدولة وتتبع المقابلات",
              },
              {
                title: "Offers",
                titleAr: "العروض",
                href: p("/employer/offers"),
                icon: "DollarSign",
                description: "Track sent offers",
                descriptionAr: "تتبع العروض المرسلة",
              },
              {
                title: "Placements",
                titleAr: "التوظيفات",
                href: p("/employer/placements"),
                icon: "UserCheck",
                description: "Confirmed hires & placements",
                descriptionAr: "التعيينات المؤكدة",
              },
            ],
          },
          {
            title: "Tools",
            titleAr: "الأدوات",
            href: p("/employer/workflow"),
            icon: "Wrench",
            description: "Hiring tools & automation",
            descriptionAr: "أدوات التوظيف والأتمتة",
            children: [
              {
                title: "Default Workflow",
                titleAr: "سير العمل الافتراضي",
                href: p("/employer/workflow"),
                icon: "GitBranch",
                description: "Default pipeline for new jobs (override per job)",
                descriptionAr: "المسار الافتراضي للوظائف الجديدة (يمكن تخصيصه لكل وظيفة)",
              },
              {
                title: "Default Matching Weights",
                titleAr: "أوزان المطابقة الافتراضية",
                href: p("/employer/matching-weights"),
                icon: "SlidersHorizontal",
                description: "Default AI scoring for new jobs (override per job)",
                descriptionAr: "الأوزان الافتراضية للمطابقة الذكية (يمكن تخصيصها لكل وظيفة)",
              },
              {
                title: "Communication Templates",
                titleAr: "قوالب الاتصالات",
                href: p("/employer/comm-templates"),
                icon: "MessageSquare",
                description: "Email templates for candidates",
                descriptionAr: "قوالب البريد الإلكتروني للمرشحين",
              },
              {
                title: "Training",
                titleAr: "التدريب",
                href: p("/employer/training"),
                icon: "BookOpen",
                description: "Training programs & courses",
                descriptionAr: "البرامج التدريبية والدورات",
              },
            ],
          },
          {
            title: "Analytics",
            titleAr: "التحليلات",
            href: p("/employer/analytics"),
            icon: "BarChart2",
            description: "Pipeline analytics & insights",
            descriptionAr: "تحليلات خط التوظيف والرؤى",
          },
          {
            title: "Messages",
            titleAr: "الرسائل",
            href: p("/employer/messages"),
            icon: "MessageSquare",
            description: "Direct messages with candidates",
            descriptionAr: "الرسائل المباشرة مع المرشحين",
          },
          {
            title: "Notifications",
            titleAr: "الإشعارات",
            href: p("/notifications"),
            icon: "Bell",
            description: "View all notifications",
            descriptionAr: "عرض جميع الإشعارات",
          },
          {
            title: "Team",
            titleAr: "الفريق",
            href: p("/employer/team"),
            icon: "Users",
            description: "Manage team members & roles",
            descriptionAr: "إدارة أعضاء الفريق والأدوار",
          },
          {
            title: "Team Activity Logs",
            titleAr: "سجل نشاط الفريق",
            href: p("/employer/team/activity-logs"),
            icon: "Activity",
            description: "View all team member activities",
            descriptionAr: "عرض جميع أنشطة أعضاء الفريق",
          },
          {
            title: "Company Settings",
            titleAr: "إعدادات الشركة",
            href: p("/employer/settings"),
            icon: "Settings",
            description: "Company profile & verification",
            descriptionAr: "الملف الشخصي للشركة والتحقق",
          },
          {
            title: "Notification Settings",
            titleAr: "إعدادات الإشعارات",
            href: p("/employer/settings?tab=notifications"),
            icon: "Bell",
            description: "Email frequency & preferences",
            descriptionAr: "تردد البريد الإلكتروني والتفضيلات",
          },
        ],
      },
    ],

    job_seeker: [
      {
        items: [
          {
            title: "Home",
            titleAr: "لوحة التحكم",
            href: p("/job-seeker"),
            icon: "LayoutDashboard",
            description: "Your job seeker home",
            descriptionAr: "نظرة عامة والمقاييس الرئيسية",
          },
          {
            title: "My Career",
            titleAr: "مسيرتي المهنية",
            href: p("/job-seeker/profile"),
            icon: "UserCircle",
            description: "Profile & career tools",
            descriptionAr: "الملف الشخصي وأدوات المهنة",
            children: [
              {
                title: "Profile",
                titleAr: "الملف الشخصي",
                href: p("/job-seeker/profile"),
                icon: "UserCircle",
                description: "Edit your profile",
                descriptionAr: "تعديل ملفك الشخصي",
              },
              {
                title: "Personal Details",
                titleAr: "البيانات الشخصية",
                href: p("/job-seeker/profile/personal-details"),
                icon: "UserCircle",
                description: "Gender, DOB, address & languages",
                descriptionAr: "الجنس، تاريخ الميلاد، العنوان واللغات",
              },
              {
                title: "Job Preferences",
                titleAr: "تفضيلات الوظيفة",
                href: p("/job-seeker/preferences"),
                icon: "Target",
                description: "Set your job matching preferences",
                descriptionAr: "تعيين تفضيلات مطابقة الوظائف",
              },
              {
                title: "Jobs",
                titleAr: "البحث عن وظيفة",
                href: p("/job-seeker/jobs"),
                icon: "Briefcase",
                description: "Browse recommended jobs",
                descriptionAr: "تصفح الوظائف المتاحة",
              },
              {
                title: "Applications",
                titleAr: "طلباتي",
                href: p("/job-seeker/applications"),
                icon: "FileText",
                description: "Track your applications",
                descriptionAr: "تتبع طلباتك",
              },
              {
                title: "Interviews",
                titleAr: "مقابلاتي",
                href: p("/job-seeker/interviews"),
                icon: "Calendar",
                description: "Upcoming interview schedule",
                descriptionAr: "جدول المقابلات القادمة",
              },
              {
                title: "Offers",
                titleAr: "العروض",
                href: p("/job-seeker/offers"),
                icon: "DollarSign",
                description: "Review received offers",
                descriptionAr: "مراجعة العروض المستلمة",
              },
              {
                title: "CV Builder",
                titleAr: "بناء السيرة الذاتية",
                href: p("/job-seeker/cv"),
                icon: "FileText",
                description: "Build & download your professional CV",
                descriptionAr: "بناء وتحميل سيرتك الذاتية المهنية",
              },
              {
                title: "Skills",
                titleAr: "المهارات",
                href: p("/job-seeker/skills"),
                icon: "Wrench",
                description: "Manage your skills",
                descriptionAr: "إدارة مهاراتك",
              },
              {
                title: "Documents",
                titleAr: "المستندات",
                href: p("/job-seeker/documents"),
                icon: "FolderOpen",
                description: "Upload certificates & docs",
                descriptionAr: "رفع الشهادات والمستندات",
              },
              {
                title: "Courses",
                titleAr: "الدورات",
                href: p("/job-seeker/courses"),
                icon: "BookOpen",
                description: "Learning & certification",
                descriptionAr: "التعلم والشهادات",
              },
            ],
          },
          {
            title: "Messages",
            titleAr: "الرسائل",
            href: p("/job-seeker/messages"),
            icon: "MessageSquare",
            description: "Chat with employers & support",
            descriptionAr: "الدردشة مع أصحاب العمل والدعم",
          },
          {
            title: "Settings",
            titleAr: "الإعدادات",
            href: p("/job-seeker/settings"),
            icon: "Settings",
            description: "Account preferences",
            descriptionAr: "تفضيلات الحساب",
          },
          {
            title: "Notification Settings",
            titleAr: "إعدادات الإشعارات",
            href: p("/job-seeker/settings/notifications"),
            icon: "Bell",
            description: "Email frequency & preferences",
            descriptionAr: "تردد البريد الإلكتروني والتفضيلات",
          },
          {
            title: "Notifications",
            titleAr: "الإشعارات",
            href: p("/notifications"),
            icon: "Bell",
            description: "View all notifications",
            descriptionAr: "عرض جميع الإشعارات",
          },
        ],
      },
    ],
  };
}

export function getNavGroups(role: UserRole, locale = "en"): NavGroup[] {
  return buildNav(locale)[role] ?? [];
}

/** Flat items for CommandMenu */
export function getAllNavItems(role: UserRole, locale = "en"): NavItem[] {
  const groups = getNavGroups(role, locale);
  return groups.flatMap((g) =>
    g.items.flatMap((item) => [item, ...(item.children ?? [])])
  );
}
