/** Additional lookup lists. [English, Arabic] unless noted. */

export const BENEFITS = [
  ["Health Insurance", "تأمين صحي"],
  ["Family Health Insurance", "تأمين صحي للعائلة"],
  ["Life Insurance", "تأمين على الحياة"],
  ["Visa Sponsorship", "كفالة الإقامة"],
  ["Family Visa Sponsorship", "كفالة إقامة العائلة"],
  ["Housing Allowance", "بدل سكن"],
  ["Company Accommodation", "سكن من الشركة"],
  ["Transportation Allowance", "بدل مواصلات"],
  ["Company Transportation", "مواصلات من الشركة"],
  ["Company Car", "سيارة من الشركة"],
  ["Fuel Allowance", "بدل وقود"],
  ["Food Allowance", "بدل طعام"],
  ["Meals Provided", "وجبات مجانية"],
  ["Mobile Phone Allowance", "بدل هاتف"],
  ["Annual Air Ticket", "تذكرة طيران سنوية"],
  ["Family Air Tickets", "تذكاير طيران للعائلة"],
  ["Paid Annual Leave", "إجازة سنوية مدفوعة"],
  ["Sick Leave", "إجازة مرضية"],
  ["Maternity Leave", "إجازة أمومة"],
  ["Paternity Leave", "إجازة أبوة"],
  ["End of Service Gratuity", "مكافأة نهاية الخدمة"],
  ["Provident Fund", "صندوق ادخار"],
  ["Pension Plan", "خطة تقاعد"],
  ["Performance Bonus", "مكافأة أداء"],
  ["Annual Bonus", "مكافأة سنوية"],
  ["Sales Commission", "عمولة مبيعات"],
  ["Overtime Pay", "أجر العمل الإضافي"],
  ["Education Allowance for Children", "بدل تعليم للأطفال"],
  ["Training & Development", "تدريب وتطوير"],
  ["Professional Certification Support", "دعم الشهادات المهنية"],
  ["Tuition Reimbursement", "تعويض الرسوم الدراسية"],
  ["Flexible Working Hours", "ساعات عمل مرنة"],
  ["Remote Work Option", "خيار العمل عن بعد"],
  ["Hybrid Work", "عمل هجين"],
  ["4-Day Work Week", "أسبوع عمل 4 أيام"],
  ["Gym Membership", "عضوية نادي رياضي"],
  ["Wellness Program", "برنامج صحة ورفاهية"],
  ["Employee Discounts", "خصومات للموظفين"],
  ["Stock Options / ESOP", "خيارات أسهم للموظفين"],
  ["Relocation Assistance", "مساعدة في الانتقال"],
  ["Laptop Provided", "توفير حاسوب محمول"],
  ["Free Parking", "مواقف سيارات مجانية"],
  ["Childcare Support", "دعم رعاية الأطفال"],
  ["Employee Referral Bonus", "مكافأة إحالة الموظفين"],
  ["Recreational Activities", "أنشطة ترفيهية"],
];

export const VISA_STATUSES = [
  ["Citizen / National", "مواطن"],
  ["Employment Visa", "تأشيرة عمل"],
  ["Visit Visa", "تأشيرة زيارة"],
  ["Tourist Visa", "تأشيرة سياحية"],
  ["Family / Spouse Sponsorship", "إقامة على كفالة العائلة"],
  ["Student Visa", "تأشيرة طالب"],
  ["Golden Visa", "الإقامة الذهبية"],
  ["Green Visa", "الإقامة الخضراء"],
  ["Freelance Visa", "تأشيرة عمل حر"],
  ["Investor / Partner Visa", "تأشيرة مستثمر / شريك"],
  ["Cancelled Visa", "تأشيرة ملغاة"],
  ["Visa Expired", "تأشيرة منتهية"],
  ["Transferable Iqama", "إقامة قابلة للنقل"],
  ["Non-Transferable Iqama", "إقامة غير قابلة للنقل"],
  ["Permanent Residence", "إقامة دائمة"],
  ["Work Permit Holder", "حامل إذن عمل"],
  ["No Visa (Outside Country)", "بدون تأشيرة (خارج الدولة)"],
  ["Requires Sponsorship", "يحتاج إلى كفالة"],
];

export const NOTICE_PERIODS = [
  ["Immediate", "فوري"],
  ["Less than 15 Days", "أقل من 15 يومًا"],
  ["15 Days", "15 يومًا"],
  ["1 Month", "شهر واحد"],
  ["2 Months", "شهران"],
  ["3 Months", "3 أشهر"],
  ["More than 3 Months", "أكثر من 3 أشهر"],
  ["Serving Notice Period", "في فترة الإشعار حاليًا"],
];

export const COMPANY_SIZES = [
  ["1-10 Employees", "1-10 موظفين"],
  ["11-50 Employees", "11-50 موظفًا"],
  ["51-200 Employees", "51-200 موظف"],
  ["201-500 Employees", "201-500 موظف"],
  ["501-1000 Employees", "501-1000 موظف"],
  ["1001-5000 Employees", "1001-5000 موظف"],
  ["5001-10000 Employees", "5001-10000 موظف"],
  ["10000+ Employees", "أكثر من 10000 موظف"],
];

/** ISO 639-1 codes; names resolved through Intl.DisplayNames at seed time. */
export const LANGUAGE_CODES = [
  "ar", "en", "hi", "ur", "ml", "ta", "te", "kn", "bn", "mr", "gu", "pa", "ne", "si",
  "tl", "id", "ms", "th", "vi", "zh", "ja", "ko", "fa", "ps", "tr", "ku", "he",
  "fr", "de", "es", "pt", "it", "nl", "ru", "uk", "pl", "ro", "el", "sv", "no", "da",
  "fi", "cs", "hu", "sr", "hr", "bg", "sw", "am", "so", "ha", "yo", "ig", "af", "zu",
  "my", "km", "lo", "mn", "kk", "uz", "az", "hy", "ka", "sq", "bs", "sk", "sl", "lt", "lv", "et",
];

/** Nationalities keyed by ISO 3166-1 alpha-2 country code: [English demonym, Arabic]. */
export const NATIONALITIES = {
  AE: ["Emirati", "إماراتي"], SA: ["Saudi", "سعودي"], QA: ["Qatari", "قطري"], KW: ["Kuwaiti", "كويتي"],
  BH: ["Bahraini", "بحريني"], OM: ["Omani", "عُماني"], YE: ["Yemeni", "يمني"], JO: ["Jordanian", "أردني"],
  LB: ["Lebanese", "لبناني"], SY: ["Syrian", "سوري"], IQ: ["Iraqi", "عراقي"], PS: ["Palestinian", "فلسطيني"],
  EG: ["Egyptian", "مصري"], SD: ["Sudanese", "سوداني"], LY: ["Libyan", "ليبي"], TN: ["Tunisian", "تونسي"],
  DZ: ["Algerian", "جزائري"], MA: ["Moroccan", "مغربي"], MR: ["Mauritanian", "موريتاني"], SO: ["Somali", "صومالي"],
  DJ: ["Djiboutian", "جيبوتي"], KM: ["Comorian", "قمري"],
  IN: ["Indian", "هندي"], PK: ["Pakistani", "باكستاني"], BD: ["Bangladeshi", "بنغلاديشي"], LK: ["Sri Lankan", "سريلانكي"],
  NP: ["Nepali", "نيبالي"], BT: ["Bhutanese", "بوتاني"], MV: ["Maldivian", "مالديفي"], AF: ["Afghan", "أفغاني"],
  IR: ["Iranian", "إيراني"], TR: ["Turkish", "تركي"],
  PH: ["Filipino", "فلبيني"], ID: ["Indonesian", "إندونيسي"], MY: ["Malaysian", "ماليزي"], SG: ["Singaporean", "سنغافوري"],
  TH: ["Thai", "تايلاندي"], VN: ["Vietnamese", "فيتنامي"], MM: ["Burmese", "بورمي"], KH: ["Cambodian", "كمبودي"],
  LA: ["Laotian", "لاوسي"], BN: ["Bruneian", "بروناوي"], CN: ["Chinese", "صيني"], JP: ["Japanese", "ياباني"],
  KR: ["South Korean", "كوري جنوبي"], TW: ["Taiwanese", "تايواني"], HK: ["Hong Konger", "هونغ كونغي"], MN: ["Mongolian", "منغولي"],
  KZ: ["Kazakh", "كازاخستاني"], UZ: ["Uzbek", "أوزبكي"], KG: ["Kyrgyz", "قيرغيزستاني"], TJ: ["Tajik", "طاجيكي"],
  TM: ["Turkmen", "تركمانستاني"], AZ: ["Azerbaijani", "أذربيجاني"], AM: ["Armenian", "أرميني"], GE: ["Georgian", "جورجي"],
  GB: ["British", "بريطاني"], IE: ["Irish", "أيرلندي"], FR: ["French", "فرنسي"], DE: ["German", "ألماني"],
  IT: ["Italian", "إيطالي"], ES: ["Spanish", "إسباني"], PT: ["Portuguese", "برتغالي"], NL: ["Dutch", "هولندي"],
  BE: ["Belgian", "بلجيكي"], LU: ["Luxembourger", "لوكسمبورغي"], CH: ["Swiss", "سويسري"], AT: ["Austrian", "نمساوي"],
  SE: ["Swedish", "سويدي"], NO: ["Norwegian", "نرويجي"], DK: ["Danish", "دانماركي"], FI: ["Finnish", "فنلندي"],
  IS: ["Icelandic", "آيسلندي"], PL: ["Polish", "بولندي"], CZ: ["Czech", "تشيكي"], SK: ["Slovak", "سلوفاكي"],
  HU: ["Hungarian", "هنغاري"], RO: ["Romanian", "روماني"], BG: ["Bulgarian", "بلغاري"], GR: ["Greek", "يوناني"],
  CY: ["Cypriot", "قبرصي"], MT: ["Maltese", "مالطي"], HR: ["Croatian", "كرواتي"], SI: ["Slovenian", "سلوفيني"],
  RS: ["Serbian", "صربي"], BA: ["Bosnian", "بوسني"], ME: ["Montenegrin", "مونتينيغري"], MK: ["Macedonian", "مقدوني"],
  AL: ["Albanian", "ألباني"], XK: ["Kosovar", "كوسوفي"], UA: ["Ukrainian", "أوكراني"], BY: ["Belarusian", "بيلاروسي"],
  MD: ["Moldovan", "مولدوفي"], RU: ["Russian", "روسي"], LT: ["Lithuanian", "ليتواني"], LV: ["Latvian", "لاتفي"], EE: ["Estonian", "إستوني"],
  US: ["American", "أمريكي"], CA: ["Canadian", "كندي"], MX: ["Mexican", "مكسيكي"], BR: ["Brazilian", "برازيلي"],
  AR: ["Argentine", "أرجنتيني"], CL: ["Chilean", "تشيلي"], CO: ["Colombian", "كولومبي"], PE: ["Peruvian", "بيروفي"],
  VE: ["Venezuelan", "فنزويلي"], EC: ["Ecuadorian", "إكوادوري"], BO: ["Bolivian", "بوليفي"], UY: ["Uruguayan", "أوروغواياني"],
  PY: ["Paraguayan", "باراغواياني"], CU: ["Cuban", "كوبي"], DO: ["Dominican", "دومينيكاني"], JM: ["Jamaican", "جامايكي"],
  TT: ["Trinidadian", "ترينيدادي"], GT: ["Guatemalan", "غواتيمالي"], HN: ["Honduran", "هندوراسي"], SV: ["Salvadoran", "سلفادوري"],
  NI: ["Nicaraguan", "نيكاراغوي"], CR: ["Costa Rican", "كوستاريكي"], PA: ["Panamanian", "بنمي"],
  AU: ["Australian", "أسترالي"], NZ: ["New Zealander", "نيوزيلندي"], FJ: ["Fijian", "فيجي"], PG: ["Papua New Guinean", "بابوا غينيا الجديدة"],
  NG: ["Nigerian", "نيجيري"], GH: ["Ghanaian", "غاني"], KE: ["Kenyan", "كيني"], UG: ["Ugandan", "أوغندي"],
  TZ: ["Tanzanian", "تنزاني"], ET: ["Ethiopian", "إثيوبي"], ER: ["Eritrean", "إريتري"], RW: ["Rwandan", "رواندي"],
  ZA: ["South African", "جنوب أفريقي"], ZW: ["Zimbabwean", "زيمبابوي"], ZM: ["Zambian", "زامبي"], MW: ["Malawian", "مالاوي"],
  MZ: ["Mozambican", "موزمبيقي"], AO: ["Angolan", "أنغولي"], NA: ["Namibian", "ناميبي"], BW: ["Botswanan", "بوتسواني"],
  CM: ["Cameroonian", "كاميروني"], CI: ["Ivorian", "إيفواري"], SN: ["Senegalese", "سنغالي"], ML: ["Malian", "مالي"],
  NE: ["Nigerien", "نيجري"], TD: ["Chadian", "تشادي"], BF: ["Burkinabe", "بوركيني"], GN: ["Guinean", "غيني"],
  SL: ["Sierra Leonean", "سيراليوني"], LR: ["Liberian", "ليبيري"], TG: ["Togolese", "توغولي"], BJ: ["Beninese", "بنيني"],
  CD: ["Congolese", "كونغولي"], GA: ["Gabonese", "غابوني"], MG: ["Malagasy", "مدغشقري"], MU: ["Mauritian", "موريشيوسي"],
  SC: ["Seychellois", "سيشلي"], SS: ["South Sudanese", "جنوب سوداني"],
};
