/** Skills grouped by category. [English, Arabic] */
export default [
  {
    category: "Programming Languages",
    skills: [
      ["Python", "بايثون"],
      ["JavaScript", "جافا سكريبت"],
      ["TypeScript", "تايب سكريبت"],
      ["Java", "جافا"],
      ["C#", "سي شارب"],
      ["C++", "سي بلس بلس"],
      ["C Programming", "لغة سي"],
      ["Go (Golang)", "جو (جولانج)"],
      ["Rust", "رست"],
      ["PHP", "بي إتش بي"],
      ["Ruby", "روبي"],
      ["Swift", "سويفت"],
      ["Kotlin", "كوتلن"],
      ["Objective-C", "أوبجكتيف سي"],
      ["Scala", "سكالا"],
      ["Dart", "دارت"],
      ["R Programming", "لغة آر"],
      ["MATLAB", "ماتلاب"],
      ["Perl", "بيرل"],
      ["Bash Scripting", "برمجة باش"],
      ["PowerShell", "باورشيل"],
      ["SQL", "إس كيو إل"],
      ["Visual Basic", "فيجوال بيسك"],
      ["VBA", "في بي إيه"],
      ["COBOL", "كوبول"],
      ["Assembly Language", "لغة التجميع"],
      ["Elixir", "إليكسير"],
      ["Haskell", "هاسكل"],
      ["Lua", "لوا"],
      ["Solidity", "سوليديتي"],
    ],
  },
  {
    category: "Web Frontend",
    skills: [
      ["HTML5", "إتش تي إم إل 5"],
      ["CSS3", "سي إس إس 3"],
      ["React", "ريأكت"],
      ["Next.js", "نكست جي إس"],
      ["Vue.js", "فيو جي إس"],
      ["Nuxt.js", "نكست (Nuxt)"],
      ["Angular", "أنجولار"],
      ["Svelte", "سفيلت"],
      ["jQuery", "جي كويري"],
      ["Tailwind CSS", "تيلويند سي إس إس"],
      ["Bootstrap", "بوتستراب"],
      ["Sass/SCSS", "ساس"],
      ["Redux", "ريدكس"],
      ["Webpack", "ويب باك"],
      ["Vite", "فيت"],
      ["Responsive Web Design", "تصميم الويب المتجاوب"],
      ["Web Accessibility (WCAG)", "إمكانية الوصول للويب"],
      ["Progressive Web Apps", "تطبيقات الويب التقدمية"],
      ["Web Performance Optimization", "تحسين أداء الويب"],
      ["Cross-Browser Compatibility", "التوافق مع المتصفحات"],
      ["Storybook", "ستوري بوك"],
      ["Three.js", "ثري جي إس"],
      ["WebSockets", "ويب سوكتس"],
      ["Material UI", "ماتيريال يو آي"],
      ["Frontend Testing (Jest/Cypress)", "اختبار الواجهات الأمامية"],
    ],
  },
  {
    category: "Backend & Frameworks",
    skills: [
      ["Node.js", "نود جي إس"],
      ["Express.js", "إكسبريس جي إس"],
      ["NestJS", "نست جي إس"],
      ["Django", "جانغو"],
      ["Flask", "فلاسك"],
      ["FastAPI", "فاست إيه بي آي"],
      ["Spring Boot", "سبرينغ بوت"],
      ["ASP.NET Core", "إيه إس بي دوت نت كور"],
      [".NET Framework", "دوت نت فريموورك"],
      ["Laravel", "لارافيل"],
      ["Symfony", "سيمفوني"],
      ["Ruby on Rails", "روبي أون ريلز"],
      ["GraphQL", "جراف كيو إل"],
      ["RESTful API Design", "تصميم واجهات REST"],
      ["gRPC", "جي آر بي سي"],
      ["Microservices Architecture", "بنية الخدمات المصغرة"],
      ["Event-Driven Architecture", "البنية المعتمدة على الأحداث"],
      ["Message Queues (RabbitMQ/Kafka)", "قوائم انتظار الرسائل"],
      ["Apache Kafka", "أباتشي كافكا"],
      ["OAuth 2.0 & JWT", "OAuth 2.0 و JWT"],
      ["Prisma ORM", "بريزما"],
      ["Hibernate", "هايبرنيت"],
      ["Entity Framework", "إنتيتي فريموورك"],
      ["Serverless Architecture", "البنية بدون خوادم"],
      ["API Documentation (Swagger/OpenAPI)", "توثيق واجهات البرمجة"],
      ["Unit Testing", "اختبار الوحدات"],
      ["Test-Driven Development", "التطوير الموجه بالاختبارات"],
      ["Object-Oriented Programming", "البرمجة كائنية التوجه"],
      ["Design Patterns", "أنماط التصميم"],
      ["Data Structures & Algorithms", "هياكل البيانات والخوارزميات"],
      ["Software Architecture", "هندسة البرمجيات"],
      ["Code Review", "مراجعة الكود"],
      ["Git Version Control", "التحكم بالإصدارات Git"],
    ],
  },
  {
    category: "Mobile",
    skills: [
      ["iOS Development", "تطوير تطبيقات iOS"],
      ["Android Development", "تطوير تطبيقات أندرويد"],
      ["React Native", "ريأكت نيتف"],
      ["Flutter", "فلاتر"],
      ["SwiftUI", "سويفت يو آي"],
      ["Jetpack Compose", "جيت باك كومبوز"],
      ["Xamarin", "زامارين"],
      ["Ionic", "أيونيك"],
      ["Mobile UI/UX Design", "تصميم واجهات الجوال"],
      ["App Store Publishing", "النشر على متجر التطبيقات"],
      ["Google Play Console", "وحدة تحكم Google Play"],
      ["Firebase", "فايربيس"],
      ["Push Notifications", "الإشعارات الفورية"],
      ["Mobile App Testing", "اختبار تطبيقات الجوال"],
      ["Mobile Security", "أمن تطبيقات الجوال"],
      ["In-App Purchases", "المشتريات داخل التطبيق"],
      ["Offline-First Architecture", "بنية العمل دون اتصال"],
    ],
  },
  {
    category: "Databases",
    skills: [
      ["MySQL", "ماي إس كيو إل"],
      ["PostgreSQL", "بوستجريس"],
      ["Microsoft SQL Server", "مايكروسوفت إس كيو إل سيرفر"],
      ["Oracle Database", "قاعدة بيانات أوراكل"],
      ["MongoDB", "مونجو دي بي"],
      ["Redis", "ريديس"],
      ["Elasticsearch", "إيلاستيك سيرش"],
      ["Cassandra", "كاساندرا"],
      ["DynamoDB", "داينامو دي بي"],
      ["SQLite", "إس كيو لايت"],
      ["Firestore", "فايرستور"],
      ["Neo4j", "نيو فور جيه"],
      ["Database Design", "تصميم قواعد البيانات"],
      ["Database Administration", "إدارة قواعد البيانات"],
      ["Query Optimization", "تحسين الاستعلامات"],
      ["Stored Procedures", "الإجراءات المخزنة"],
      ["Data Modeling", "نمذجة البيانات"],
      ["Data Warehousing", "مستودعات البيانات"],
      ["ETL Development", "تطوير ETL"],
      ["Database Backup & Recovery", "النسخ الاحتياطي والاستعادة"],
      ["Snowflake", "سنوفليك"],
      ["Google BigQuery", "جوجل بيج كويري"],
      ["Supabase", "سوبابيس"],
    ],
  },
  {
    category: "Cloud & DevOps",
    skills: [
      ["Amazon Web Services (AWS)", "أمازون ويب سيرفيسز"],
      ["Microsoft Azure", "مايكروسوفت أزور"],
      ["Google Cloud Platform", "منصة جوجل السحابية"],
      ["Oracle Cloud", "أوراكل كلاود"],
      ["Docker", "دوكر"],
      ["Kubernetes", "كوبرنيتس"],
      ["Terraform", "تيرافورم"],
      ["Ansible", "أنسبل"],
      ["Jenkins", "جنكينز"],
      ["GitHub Actions", "جيت هاب أكشنز"],
      ["GitLab CI/CD", "جيت لاب CI/CD"],
      ["CI/CD Pipelines", "خطوط التكامل والنشر المستمر"],
      ["Linux Administration", "إدارة لينكس"],
      ["Windows Server", "ويندوز سيرفر"],
      ["Nginx", "إنجن إكس"],
      ["Apache HTTP Server", "خادم أباتشي"],
      ["Infrastructure as Code", "البنية التحتية كتعليمات برمجية"],
      ["Monitoring (Prometheus/Grafana)", "المراقبة (بروميثيوس/جرافانا)"],
      ["Logging (ELK Stack)", "إدارة السجلات (ELK)"],
      ["Site Reliability Engineering", "هندسة موثوقية المواقع"],
      ["Cloud Cost Optimization", "تحسين تكاليف السحابة"],
      ["Cloud Migration", "الترحيل إلى السحابة"],
      ["Helm Charts", "هيلم تشارتس"],
      ["VMware vSphere", "في إم وير"],
      ["Virtualization", "المحاكاة الافتراضية"],
      ["Load Balancing", "موازنة الأحمال"],
      ["Disaster Recovery Planning", "تخطيط التعافي من الكوارث"],
      ["Datadog", "داتادوج"],
      ["Vercel", "فيرسل"],
    ],
  },
  {
    category: "Data Science & AI",
    skills: [
      ["Machine Learning", "تعلم الآلة"],
      ["Deep Learning", "التعلم العميق"],
      ["Natural Language Processing", "معالجة اللغة الطبيعية"],
      ["Computer Vision", "الرؤية الحاسوبية"],
      ["Generative AI", "الذكاء الاصطناعي التوليدي"],
      ["Large Language Models (LLMs)", "نماذج اللغة الكبيرة"],
      ["Prompt Engineering", "هندسة الأوامر"],
      ["TensorFlow", "تنسرفلو"],
      ["PyTorch", "بايتورش"],
      ["Scikit-learn", "سايكت ليرن"],
      ["Keras", "كيراس"],
      ["Pandas", "بانداز"],
      ["NumPy", "نمباي"],
      ["Data Analysis", "تحليل البيانات"],
      ["Data Visualization", "تصور البيانات"],
      ["Statistical Analysis", "التحليل الإحصائي"],
      ["Predictive Modeling", "النمذجة التنبؤية"],
      ["A/B Testing", "اختبار A/B"],
      ["Power BI", "باور بي آي"],
      ["Tableau", "تابلو"],
      ["Looker", "لوكر"],
      ["Apache Spark", "أباتشي سبارك"],
      ["Hadoop", "هادوب"],
      ["Databricks", "داتابريكس"],
      ["Data Engineering", "هندسة البيانات"],
      ["Apache Airflow", "أباتشي إيرفلو"],
      ["dbt", "دي بي تي"],
      ["MLOps", "عمليات تعلم الآلة"],
      ["Recommendation Systems", "أنظمة التوصية"],
      ["Time Series Analysis", "تحليل السلاسل الزمنية"],
      ["Reinforcement Learning", "التعلم المعزز"],
      ["Hugging Face Transformers", "هاجينج فيس"],
      ["LangChain", "لانج تشين"],
      ["Vector Databases", "قواعد البيانات المتجهة"],
      ["Retrieval-Augmented Generation (RAG)", "التوليد المعزز بالاسترجاع"],
      ["OpenAI API", "واجهة OpenAI"],
      ["Jupyter Notebooks", "دفاتر جوبيتر"],
      ["Big Data Analytics", "تحليلات البيانات الضخمة"],
      ["Speech Recognition", "التعرف على الكلام"],
    ],
  },
  {
    category: "Cybersecurity",
    skills: [
      ["Information Security", "أمن المعلومات"],
      ["Network Security", "أمن الشبكات"],
      ["Penetration Testing", "اختبار الاختراق"],
      ["Ethical Hacking", "الاختراق الأخلاقي"],
      ["Vulnerability Assessment", "تقييم الثغرات الأمنية"],
      ["Security Operations Center (SOC)", "مركز العمليات الأمنية"],
      ["SIEM (Splunk/QRadar)", "أنظمة SIEM"],
      ["Incident Response", "الاستجابة للحوادث"],
      ["Threat Intelligence", "استخبارات التهديدات"],
      ["Digital Forensics", "التحقيق الجنائي الرقمي"],
      ["Identity & Access Management", "إدارة الهوية والوصول"],
      ["Firewall Management", "إدارة جدار الحماية"],
      ["Endpoint Security", "أمن نقاط النهاية"],
      ["Cloud Security", "أمن السحابة"],
      ["Application Security", "أمن التطبيقات"],
      ["OWASP Top 10", "قائمة OWASP العشر"],
      ["Cryptography", "التشفير"],
      ["Public Key Infrastructure (PKI)", "البنية التحتية للمفاتيح العامة"],
      ["Security Auditing", "التدقيق الأمني"],
      ["ISO 27001 Implementation", "تطبيق ISO 27001"],
      ["Risk Assessment", "تقييم المخاطر"],
      ["Data Loss Prevention", "منع فقدان البيانات"],
      ["Malware Analysis", "تحليل البرمجيات الخبيثة"],
      ["Security Awareness Training", "التوعية الأمنية"],
      ["Zero Trust Architecture", "بنية الثقة الصفرية"],
      ["Kali Linux", "كالي لينكس"],
      ["Burp Suite", "بيرب سويت"],
      ["Wireshark", "وايرشارك"],
      ["Metasploit", "ميتاسبلويت"],
      ["DevSecOps", "ديف سيك أوبس"],
    ],
  },
  {
    category: "Networking & IT Support",
    skills: [
      ["Network Administration", "إدارة الشبكات"],
      ["TCP/IP", "بروتوكول TCP/IP"],
      ["Cisco Routing & Switching", "التوجيه والتبديل سيسكو"],
      ["Cisco IOS", "نظام سيسكو IOS"],
      ["LAN/WAN", "الشبكات المحلية والواسعة"],
      ["VPN Configuration", "إعداد الشبكات الافتراضية الخاصة"],
      ["DNS & DHCP", "خدمات DNS و DHCP"],
      ["VLAN Configuration", "إعداد الشبكات الافتراضية VLAN"],
      ["Wireless Networking", "الشبكات اللاسلكية"],
      ["Network Troubleshooting", "استكشاف أخطاء الشبكات"],
      ["Structured Cabling", "الكابلات المهيكلة"],
      ["Fiber Optics", "الألياف الضوئية"],
      ["IT Help Desk", "مكتب الدعم التقني"],
      ["Technical Support", "الدعم الفني"],
      ["Desktop Support", "دعم أجهزة الحاسوب"],
      ["Hardware Troubleshooting", "استكشاف أعطال الأجهزة"],
      ["Active Directory", "أكتيف دايركتوري"],
      ["Microsoft 365 Administration", "إدارة مايكروسوفت 365"],
      ["Microsoft Exchange", "مايكروسوفت إكستشينج"],
      ["Microsoft Intune", "مايكروسوفت إنتون"],
      ["ITIL Service Management", "إدارة خدمات ITIL"],
      ["ServiceNow", "سيرفس ناو"],
      ["Jira Service Management", "جيرا لإدارة الخدمات"],
      ["System Administration", "إدارة الأنظمة"],
      ["macOS Support", "دعم نظام macOS"],
      ["Printer & Peripheral Support", "دعم الطابعات والملحقات"],
      ["Remote Desktop Support", "الدعم عن بُعد"],
      ["IT Asset Management", "إدارة الأصول التقنية"],
      ["Backup Solutions (Veeam)", "حلول النسخ الاحتياطي"],
      ["SD-WAN", "الشبكات الواسعة المعرفة برمجياً"],
      ["Fortinet FortiGate", "فورتينت فورتي جيت"],
      ["Palo Alto Networks", "بالو ألتو نتووركس"],
      ["CCTV & Access Control Systems", "أنظمة المراقبة والتحكم بالدخول"],
      ["Telecom Systems (VoIP/PBX)", "أنظمة الاتصالات (VoIP/PBX)"],
      ["IoT Systems", "أنظمة إنترنت الأشياء"],
    ],
  },
  {
    category: "ERP/CRM & Business Software",
    skills: [
      ["SAP ERP", "ساب ERP"],
      ["SAP S/4HANA", "ساب S/4HANA"],
      ["SAP FICO", "ساب FICO"],
      ["SAP MM", "ساب MM"],
      ["SAP SD", "ساب SD"],
      ["SAP HCM/SuccessFactors", "ساب HCM/SuccessFactors"],
      ["SAP ABAP", "ساب ABAP"],
      ["Oracle ERP Cloud", "أوراكل ERP كلاود"],
      ["Oracle Fusion", "أوراكل فيوجن"],
      ["Oracle E-Business Suite", "أوراكل إي بزنس سويت"],
      ["Microsoft Dynamics 365", "مايكروسوفت داينامكس 365"],
      ["Microsoft Dynamics NAV/Business Central", "داينامكس بزنس سنترال"],
      ["Salesforce CRM", "سيلزفورس"],
      ["Salesforce Administration", "إدارة سيلزفورس"],
      ["HubSpot CRM", "هاب سبوت"],
      ["Zoho CRM", "زوهو CRM"],
      ["Odoo", "أودو"],
      ["NetSuite", "نت سويت"],
      ["Workday", "ووركداي"],
      ["Sage", "سيج"],
      ["Tally ERP", "تالي ERP"],
      ["QuickBooks", "كويك بوكس"],
      ["Xero", "زيرو"],
      ["Focus ERP", "فوكس ERP"],
      ["Infor ERP", "إنفور ERP"],
      ["ERP Implementation", "تنفيذ أنظمة ERP"],
      ["CRM Administration", "إدارة أنظمة CRM"],
      ["Business Process Mapping", "رسم خرائط العمليات"],
      ["Robotic Process Automation (RPA)", "أتمتة العمليات الروبوتية"],
      ["UiPath", "يو آي باث"],
      ["Power Automate", "باور أوتوميت"],
      ["Power Apps", "باور آبس"],
      ["SharePoint", "شير بوينت"],
      ["Zapier", "زابير"],
      ["Business Intelligence", "ذكاء الأعمال"],
    ],
  },
  {
    category: "Design & Creative Tools",
    skills: [
      ["Adobe Photoshop", "أدوبي فوتوشوب"],
      ["Adobe Illustrator", "أدوبي إليستريتور"],
      ["Adobe InDesign", "أدوبي إن ديزاين"],
      ["Adobe After Effects", "أدوبي أفتر إفكتس"],
      ["Adobe Premiere Pro", "أدوبي بريمير برو"],
      ["Adobe XD", "أدوبي إكس دي"],
      ["Adobe Lightroom", "أدوبي لايتروم"],
      ["Figma", "فيجما"],
      ["Sketch", "سكتش"],
      ["Canva", "كانفا"],
      ["CorelDRAW", "كوريل درو"],
      ["Blender", "بلندر"],
      ["Cinema 4D", "سينما فور دي"],
      ["Autodesk Maya", "أوتوديسك مايا"],
      ["3ds Max", "ثري دي إس ماكس"],
      ["Final Cut Pro", "فاينل كت برو"],
      ["DaVinci Resolve", "دافينشي ريزولف"],
      ["UI/UX Design", "تصميم تجربة وواجهة المستخدم"],
      ["User Research", "أبحاث المستخدمين"],
      ["Wireframing & Prototyping", "التخطيط الهيكلي والنماذج الأولية"],
      ["Graphic Design", "التصميم الجرافيكي"],
      ["Brand Identity Design", "تصميم الهوية البصرية"],
      ["Logo Design", "تصميم الشعارات"],
      ["Typography", "فن الطباعة والخطوط"],
      ["Arabic Calligraphy & Typography", "الخط العربي والطباعة العربية"],
      ["Motion Graphics", "الرسوم المتحركة"],
      ["Video Editing", "مونتاج الفيديو"],
      ["Photography", "التصوير الفوتوغرافي"],
      ["Videography", "تصوير الفيديو"],
      ["3D Modeling", "النمذجة ثلاثية الأبعاد"],
      ["Animation", "التحريك"],
      ["Illustration", "الرسم التوضيحي"],
      ["Print Design", "تصميم المطبوعات"],
      ["Packaging Design", "تصميم التغليف"],
      ["Interior Design", "التصميم الداخلي"],
      ["Design Systems", "أنظمة التصميم"],
      ["Sound Design", "تصميم الصوت"],
      ["Color Theory", "نظرية الألوان"],
    ],
  },
  {
    category: "Digital Marketing",
    skills: [
      ["Search Engine Optimization (SEO)", "تحسين محركات البحث"],
      ["Search Engine Marketing (SEM)", "التسويق عبر محركات البحث"],
      ["Google Ads", "إعلانات جوجل"],
      ["Meta Ads (Facebook/Instagram)", "إعلانات ميتا (فيسبوك/إنستغرام)"],
      ["TikTok Ads", "إعلانات تيك توك"],
      ["Snapchat Ads", "إعلانات سناب شات"],
      ["LinkedIn Marketing", "التسويق عبر لينكد إن"],
      ["Social Media Marketing", "التسويق عبر وسائل التواصل الاجتماعي"],
      ["Social Media Management", "إدارة وسائل التواصل الاجتماعي"],
      ["Content Marketing", "تسويق المحتوى"],
      ["Content Writing", "كتابة المحتوى"],
      ["Copywriting", "كتابة الإعلانات"],
      ["Arabic Content Writing", "كتابة المحتوى العربي"],
      ["Email Marketing", "التسويق عبر البريد الإلكتروني"],
      ["Marketing Automation", "أتمتة التسويق"],
      ["Google Analytics", "جوجل أناليتكس"],
      ["Google Tag Manager", "جوجل تاج مانجر"],
      ["Conversion Rate Optimization", "تحسين معدل التحويل"],
      ["Performance Marketing", "التسويق بالأداء"],
      ["Affiliate Marketing", "التسويق بالعمولة"],
      ["Influencer Marketing", "التسويق عبر المؤثرين"],
      ["Brand Management", "إدارة العلامة التجارية"],
      ["Marketing Strategy", "استراتيجية التسويق"],
      ["Market Research", "أبحاث السوق"],
      ["Public Relations", "العلاقات العامة"],
      ["Event Marketing", "تسويق الفعاليات"],
      ["Growth Hacking", "التسويق السريع للنمو"],
      ["E-commerce Marketing", "تسويق التجارة الإلكترونية"],
      ["Shopify", "شوبيفاي"],
      ["WordPress", "ووردبريس"],
      ["Mailchimp", "ميل تشيمب"],
      ["Hootsuite", "هوت سويت"],
      ["Semrush", "سيم راش"],
      ["Video Marketing", "التسويق بالفيديو"],
      ["Community Management", "إدارة المجتمعات الرقمية"],
      ["Media Planning & Buying", "التخطيط والشراء الإعلامي"],
      ["Programmatic Advertising", "الإعلانات البرمجية"],
      ["App Store Optimization (ASO)", "تحسين متجر التطبيقات"],
    ],
  },
  {
    category: "Sales & Business Development",
    skills: [
      ["B2B Sales", "المبيعات بين الشركات"],
      ["B2C Sales", "مبيعات المستهلكين"],
      ["Business Development", "تطوير الأعمال"],
      ["Lead Generation", "توليد العملاء المحتملين"],
      ["Cold Calling", "المكالمات الباردة"],
      ["Negotiation", "التفاوض"],
      ["Account Management", "إدارة الحسابات"],
      ["Key Account Management", "إدارة الحسابات الرئيسية"],
      ["Sales Strategy", "استراتيجية المبيعات"],
      ["Sales Forecasting", "التنبؤ بالمبيعات"],
      ["Sales Pipeline Management", "إدارة خط المبيعات"],
      ["Client Relationship Management", "إدارة علاقات العملاء"],
      ["Retail Sales", "مبيعات التجزئة"],
      ["Inside Sales", "المبيعات الداخلية"],
      ["Field Sales", "المبيعات الميدانية"],
      ["Telesales", "المبيعات الهاتفية"],
      ["Real Estate Sales", "مبيعات العقارات"],
      ["Insurance Sales", "مبيعات التأمين"],
      ["Automotive Sales", "مبيعات السيارات"],
      ["Pharmaceutical Sales", "المبيعات الدوائية"],
      ["Channel Sales", "المبيعات عبر القنوات"],
      ["Tender Management", "إدارة المناقصات"],
      ["Proposal Writing", "كتابة العروض"],
      ["Presentation Skills", "مهارات العرض والتقديم"],
      ["Upselling & Cross-Selling", "البيع الإضافي والمتقاطع"],
      ["Customer Retention", "الاحتفاظ بالعملاء"],
      ["Merchandising", "تنسيق البضائع"],
      ["Pricing Strategy", "استراتيجية التسعير"],
      ["Partnership Development", "تطوير الشراكات"],
      ["Sales Training", "تدريب المبيعات"],
      ["Customer Service", "خدمة العملاء"],
      ["Call Center Operations", "عمليات مركز الاتصال"],
      ["Complaint Handling", "معالجة الشكاوى"],
      ["Point of Sale (POS) Systems", "أنظمة نقاط البيع"],
      ["Franchise Development", "تطوير الامتياز التجاري"],
    ],
  },
  {
    category: "Finance & Accounting",
    skills: [
      ["Financial Accounting", "المحاسبة المالية"],
      ["Management Accounting", "المحاسبة الإدارية"],
      ["Cost Accounting", "محاسبة التكاليف"],
      ["Financial Reporting", "التقارير المالية"],
      ["Financial Analysis", "التحليل المالي"],
      ["Financial Modeling", "النمذجة المالية"],
      ["Budgeting & Forecasting", "إعداد الميزانيات والتنبؤ"],
      ["Accounts Payable", "الحسابات الدائنة"],
      ["Accounts Receivable", "الحسابات المدينة"],
      ["General Ledger", "دفتر الأستاذ العام"],
      ["Bank Reconciliation", "التسويات البنكية"],
      ["Payroll Processing", "معالجة الرواتب"],
      ["IFRS", "المعايير الدولية للتقارير المالية"],
      ["GAAP", "مبادئ المحاسبة المقبولة عموماً"],
      ["VAT Compliance (GCC)", "الامتثال لضريبة القيمة المضافة"],
      ["Corporate Tax (UAE)", "ضريبة الشركات (الإمارات)"],
      ["Zakat & Tax (Saudi Arabia)", "الزكاة والضريبة (السعودية)"],
      ["Taxation", "الضرائب"],
      ["Internal Audit", "التدقيق الداخلي"],
      ["External Audit", "التدقيق الخارجي"],
      ["Treasury Management", "إدارة الخزينة"],
      ["Cash Flow Management", "إدارة التدفقات النقدية"],
      ["Credit Analysis", "تحليل الائتمان"],
      ["Risk Management", "إدارة المخاطر"],
      ["Investment Analysis", "تحليل الاستثمار"],
      ["Portfolio Management", "إدارة المحافظ"],
      ["Corporate Finance", "التمويل المؤسسي"],
      ["Mergers & Acquisitions", "الاندماج والاستحواذ"],
      ["Valuation", "التقييم المالي"],
      ["Islamic Banking & Finance", "الصيرفة والتمويل الإسلامي"],
      ["Sharia-Compliant Products", "المنتجات المتوافقة مع الشريعة"],
      ["Trade Finance", "تمويل التجارة"],
      ["Wealth Management", "إدارة الثروات"],
      ["Anti-Money Laundering (AML)", "مكافحة غسل الأموال"],
      ["Know Your Customer (KYC)", "اعرف عميلك"],
      ["Financial Planning & Analysis (FP&A)", "التخطيط والتحليل المالي"],
      ["Fixed Asset Management", "إدارة الأصول الثابتة"],
      ["Cost Control", "مراقبة التكاليف"],
      ["Advanced Excel", "إكسل المتقدم"],
      ["Bookkeeping", "مسك الدفاتر"],
      ["Insurance Underwriting", "الاكتتاب التأميني"],
      ["Claims Processing", "معالجة المطالبات"],
      ["Fintech", "التقنية المالية"],
      ["Bloomberg Terminal", "منصة بلومبرغ"],
    ],
  },
  {
    category: "HR & Recruitment",
    skills: [
      ["Talent Acquisition", "استقطاب المواهب"],
      ["Recruitment", "التوظيف"],
      ["Headhunting", "البحث عن الكفاءات"],
      ["Sourcing", "البحث عن المرشحين"],
      ["Interviewing", "إجراء المقابلات"],
      ["Competency-Based Interviewing", "المقابلات القائمة على الكفاءات"],
      ["Onboarding", "التهيئة والإدماج"],
      ["Employee Relations", "علاقات الموظفين"],
      ["Performance Management", "إدارة الأداء"],
      ["Compensation & Benefits", "التعويضات والمزايا"],
      ["HR Policies & Procedures", "سياسات وإجراءات الموارد البشرية"],
      ["UAE Labour Law", "قانون العمل الإماراتي"],
      ["Saudi Labour Law", "نظام العمل السعودي"],
      ["GCC Labour Laws", "قوانين العمل في دول الخليج"],
      ["Visa & Immigration Processing", "إجراءات التأشيرات والإقامة"],
      ["MOHRE & WPS Compliance", "الامتثال لوزارة الموارد البشرية ونظام حماية الأجور"],
      ["Emiratisation / Saudisation", "التوطين (التوطين الإماراتي/السعودة)"],
      ["Learning & Development", "التعلم والتطوير"],
      ["Training Needs Analysis", "تحليل الاحتياجات التدريبية"],
      ["Succession Planning", "تخطيط التعاقب"],
      ["Workforce Planning", "تخطيط القوى العاملة"],
      ["HR Analytics", "تحليلات الموارد البشرية"],
      ["HRIS", "نظم معلومات الموارد البشرية"],
      ["Applicant Tracking Systems (ATS)", "أنظمة تتبع المتقدمين"],
      ["LinkedIn Recruiter", "لينكد إن ريكروتر"],
      ["Employer Branding", "بناء العلامة التجارية لجهة العمل"],
      ["Organizational Development", "التطوير التنظيمي"],
      ["Change Management", "إدارة التغيير"],
      ["Employee Engagement", "إشراك الموظفين"],
      ["Grievance Handling", "معالجة التظلمات"],
      ["Job Analysis & Descriptions", "تحليل الوظائف والتوصيف الوظيفي"],
      ["Psychometric Assessment", "التقييم النفسي والقياسي"],
      ["Payroll Administration", "إدارة الرواتب"],
      ["Diversity & Inclusion", "التنوع والشمول"],
      ["HR Business Partnering", "شراكة أعمال الموارد البشرية"],
      ["Exit Management", "إدارة إنهاء الخدمة"],
    ],
  },
  {
    category: "Project & Product Management",
    skills: [
      ["Project Management", "إدارة المشاريع"],
      ["Agile Methodologies", "منهجيات أجايل"],
      ["Scrum", "سكرم"],
      ["Kanban", "كانبان"],
      ["Waterfall Methodology", "منهجية الشلال"],
      ["PRINCE2 Methodology", "منهجية PRINCE2"],
      ["Product Management", "إدارة المنتجات"],
      ["Product Roadmapping", "خارطة طريق المنتج"],
      ["Product Strategy", "استراتيجية المنتج"],
      ["Backlog Management", "إدارة قائمة المهام"],
      ["User Story Writing", "كتابة قصص المستخدم"],
      ["Stakeholder Management", "إدارة أصحاب المصلحة"],
      ["Requirements Gathering", "جمع المتطلبات"],
      ["Business Analysis", "تحليل الأعمال"],
      ["Project Scheduling", "جدولة المشاريع"],
      ["Project Budgeting", "إعداد ميزانيات المشاريع"],
      ["Scope Management", "إدارة النطاق"],
      ["Resource Planning", "تخطيط الموارد"],
      ["Program Management", "إدارة البرامج"],
      ["Portfolio Management (PMO)", "إدارة محفظة المشاريع (PMO)"],
      ["Jira", "جيرا"],
      ["Confluence", "كونفلوينس"],
      ["Trello", "تريلو"],
      ["Asana", "أسانا"],
      ["Monday.com", "منداي دوت كوم"],
      ["Microsoft Project", "مايكروسوفت بروجكت"],
      ["Primavera P6", "بريمافيرا P6"],
      ["Notion", "نوشن"],
      ["OKR Setting", "تحديد الأهداف والنتائج الرئيسية"],
      ["KPI Development", "تطوير مؤشرات الأداء"],
      ["Go-to-Market Strategy", "استراتيجية دخول السوق"],
      ["Product Analytics", "تحليلات المنتج"],
      ["Release Management", "إدارة الإصدارات"],
      ["Vendor Management", "إدارة الموردين"],
      ["Contract Management", "إدارة العقود"],
      ["Lean Management", "الإدارة الرشيقة"],
      ["Process Improvement", "تحسين العمليات"],
      ["Digital Transformation", "التحول الرقمي"],
      ["Strategic Planning", "التخطيط الاستراتيجي"],
    ],
  },
  {
    category: "Engineering & CAD",
    skills: [
      ["AutoCAD", "أوتوكاد"],
      ["Revit", "ريفيت"],
      ["SolidWorks", "سوليدووركس"],
      ["CATIA", "كاتيا"],
      ["Autodesk Inventor", "أوتوديسك إنفنتور"],
      ["Fusion 360", "فيوجن 360"],
      ["SketchUp", "سكتش أب"],
      ["Civil 3D", "سيفل ثري دي"],
      ["STAAD.Pro", "ستاد برو"],
      ["ETABS", "إيتابس"],
      ["SAP2000", "ساب 2000"],
      ["Tekla Structures", "تيكلا ستركتشرز"],
      ["Navisworks", "نافيسووركس"],
      ["BIM (Building Information Modeling)", "نمذجة معلومات البناء"],
      ["ANSYS", "أنسيس"],
      ["Finite Element Analysis", "تحليل العناصر المحدودة"],
      ["MATLAB Simulink", "ماتلاب سيميولينك"],
      ["Mechanical Design", "التصميم الميكانيكي"],
      ["Electrical Design", "التصميم الكهربائي"],
      ["Structural Engineering", "الهندسة الإنشائية"],
      ["Civil Engineering", "الهندسة المدنية"],
      ["Mechanical Engineering", "الهندسة الميكانيكية"],
      ["Electrical Engineering", "الهندسة الكهربائية"],
      ["Chemical Engineering", "الهندسة الكيميائية"],
      ["HVAC Design", "تصميم التكييف والتهوية"],
      ["MEP Engineering", "الهندسة الميكانيكية والكهربائية والسباكة"],
      ["Plumbing Design", "تصميم السباكة"],
      ["Fire Protection Systems", "أنظمة الحماية من الحرائق"],
      ["Geotechnical Engineering", "الهندسة الجيوتقنية"],
      ["Surveying", "المساحة"],
      ["GIS (ArcGIS/QGIS)", "نظم المعلومات الجغرافية"],
      ["PLC Programming", "برمجة وحدات التحكم المنطقية"],
      ["SCADA Systems", "أنظمة سكادا"],
      ["Industrial Automation", "الأتمتة الصناعية"],
      ["Robotics", "الروبوتات"],
      ["Embedded Systems", "الأنظمة المدمجة"],
      ["PCB Design", "تصميم الدوائر المطبوعة"],
      ["Instrumentation & Control", "الأجهزة الدقيقة والتحكم"],
      ["Power Systems", "أنظمة القوى الكهربائية"],
      ["Renewable Energy Systems", "أنظمة الطاقة المتجددة"],
      ["Solar PV Design", "تصميم أنظمة الطاقة الشمسية"],
      ["Technical Drawing", "الرسم الهندسي"],
      ["Quality Engineering", "هندسة الجودة"],
      ["Reliability Engineering", "هندسة الموثوقية"],
      ["Value Engineering", "هندسة القيمة"],
      ["Failure Mode & Effects Analysis (FMEA)", "تحليل أنماط الفشل وتأثيراتها"],
      ["Sustainability & LEED", "الاستدامة ومعايير LEED"],
      ["Estidama Pearl Rating", "نظام استدامة بيرل"],
    ],
  },
  {
    category: "Construction & Trades",
    skills: [
      ["Construction Management", "إدارة الإنشاءات"],
      ["Site Supervision", "الإشراف على الموقع"],
      ["Quantity Surveying", "حساب الكميات"],
      ["Cost Estimation", "تقدير التكاليف"],
      ["Bill of Quantities (BOQ)", "جداول الكميات"],
      ["FIDIC Contracts", "عقود الفيديك"],
      ["Construction Planning", "تخطيط الإنشاءات"],
      ["Construction Safety (HSE)", "السلامة في مواقع البناء"],
      ["Building Codes & Regulations", "أكواد ولوائح البناء"],
      ["Dubai Municipality Approvals", "موافقات بلدية دبي"],
      ["Concrete Technology", "تكنولوجيا الخرسانة"],
      ["Steel Fabrication", "تصنيع الهياكل الفولاذية"],
      ["Welding (MIG/TIG/Arc)", "اللحام (MIG/TIG/قوس)"],
      ["Pipe Fitting", "تركيب الأنابيب"],
      ["Plumbing", "السباكة"],
      ["Electrical Installation", "التمديدات الكهربائية"],
      ["HVAC Installation & Maintenance", "تركيب وصيانة التكييف"],
      ["Carpentry", "النجارة"],
      ["Masonry", "البناء بالطوب"],
      ["Painting & Decorating", "الطلاء والديكور"],
      ["Tiling", "تركيب البلاط"],
      ["Scaffolding", "السقالات"],
      ["Crane Operation", "تشغيل الرافعات"],
      ["Heavy Equipment Operation", "تشغيل المعدات الثقيلة"],
      ["Excavator Operation", "تشغيل الحفارات"],
      ["Rigging & Lifting", "التزوير والرفع"],
      ["Facade & Cladding", "الواجهات والتكسية"],
      ["Interior Fit-Out", "التشطيبات الداخلية"],
      ["Joinery", "أعمال النجارة الدقيقة"],
      ["Landscaping", "تنسيق الحدائق"],
      ["Road Construction", "إنشاء الطرق"],
      ["Infrastructure Projects", "مشاريع البنية التحتية"],
      ["Facilities Management", "إدارة المرافق"],
      ["Building Maintenance", "صيانة المباني"],
      ["Elevator & Escalator Maintenance", "صيانة المصاعد والسلالم المتحركة"],
      ["Snagging & Handover", "فحص العيوب والتسليم"],
      ["Method Statements", "بيانات طرق التنفيذ"],
      ["Material Procurement", "شراء المواد"],
      ["Shop Drawings", "الرسومات التنفيذية"],
      ["Project Handover Documentation", "وثائق تسليم المشروع"],
    ],
  },
  {
    category: "Oil, Gas & Industrial",
    skills: [
      ["Oil & Gas Operations", "عمليات النفط والغاز"],
      ["Upstream Operations", "عمليات الاستكشاف والإنتاج"],
      ["Downstream Operations", "عمليات التكرير والتوزيع"],
      ["Drilling Operations", "عمليات الحفر"],
      ["Well Engineering", "هندسة الآبار"],
      ["Reservoir Engineering", "هندسة المكامن"],
      ["Petroleum Engineering", "هندسة البترول"],
      ["Process Engineering", "هندسة العمليات"],
      ["Piping Design", "تصميم الأنابيب"],
      ["Pipeline Engineering", "هندسة خطوط الأنابيب"],
      ["Offshore Operations", "العمليات البحرية"],
      ["Refinery Operations", "عمليات المصافي"],
      ["Petrochemicals", "البتروكيماويات"],
      ["LNG Operations", "عمليات الغاز الطبيعي المسال"],
      ["HAZOP Studies", "دراسات HAZOP"],
      ["Process Safety Management", "إدارة سلامة العمليات"],
      ["Permit to Work Systems", "أنظمة تصاريح العمل"],
      ["Health, Safety & Environment (HSE)", "الصحة والسلامة والبيئة"],
      ["Risk-Based Inspection", "الفحص القائم على المخاطر"],
      ["Non-Destructive Testing (NDT)", "الفحص غير المدمر"],
      ["Corrosion Control", "مكافحة التآكل"],
      ["Rotating Equipment", "المعدات الدوارة"],
      ["Static Equipment", "المعدات الثابتة"],
      ["Pressure Vessels", "أوعية الضغط"],
      ["Valve Maintenance", "صيانة الصمامات"],
      ["Pump & Compressor Maintenance", "صيانة المضخات والضواغط"],
      ["Turbine Operations", "تشغيل التوربينات"],
      ["Boiler Operations", "تشغيل الغلايات"],
      ["Mechanical Maintenance", "الصيانة الميكانيكية"],
      ["Electrical Maintenance", "الصيانة الكهربائية"],
      ["Preventive Maintenance", "الصيانة الوقائية"],
      ["Predictive Maintenance", "الصيانة التنبؤية"],
      ["Shutdown & Turnaround Management", "إدارة الإغلاق والصيانة الشاملة"],
      ["Commissioning & Start-Up", "التشغيل التجريبي والبدء"],
      ["Asset Integrity Management", "إدارة سلامة الأصول"],
      ["Production Planning", "تخطيط الإنتاج"],
      ["Manufacturing Operations", "عمليات التصنيع"],
      ["Lean Manufacturing", "التصنيع الرشيق"],
      ["Six Sigma Methodology", "منهجية ستة سيجما"],
      ["Total Quality Management", "إدارة الجودة الشاملة"],
      ["Quality Control (QC)", "مراقبة الجودة"],
      ["Quality Assurance (QA)", "ضمان الجودة"],
      ["ISO 9001 Quality Management", "إدارة الجودة ISO 9001"],
      ["ISO 14001 Environmental Management", "الإدارة البيئية ISO 14001"],
      ["ISO 45001 Occupational Health & Safety", "السلامة المهنية ISO 45001"],
      ["API Standards", "معايير API"],
      ["ASME Codes", "أكواد ASME"],
      ["CNC Machining", "التشغيل بآلات CNC"],
      ["Machining & Fabrication", "التشغيل والتصنيع الميكانيكي"],
      ["Utilities Operations (Water/Power)", "تشغيل المرافق (مياه/كهرباء)"],
      ["Water Treatment", "معالجة المياه"],
      ["Desalination", "تحلية المياه"],
      ["Mining Operations", "عمليات التعدين"],
      ["Environmental Impact Assessment", "تقييم الأثر البيئي"],
      ["Waste Management", "إدارة النفايات"],
    ],
  },
  {
    category: "Healthcare & Medical",
    skills: [
      ["Patient Care", "رعاية المرضى"],
      ["Nursing", "التمريض"],
      ["Critical Care Nursing", "تمريض العناية المركزة"],
      ["Emergency Medicine", "طب الطوارئ"],
      ["General Medicine", "الطب العام"],
      ["Pediatrics", "طب الأطفال"],
      ["Obstetrics & Gynecology", "أمراض النساء والتوليد"],
      ["Cardiology", "أمراض القلب"],
      ["Orthopedics", "جراحة العظام"],
      ["Dermatology", "الأمراض الجلدية"],
      ["Dentistry", "طب الأسنان"],
      ["Dental Assisting", "مساعدة طب الأسنان"],
      ["Anesthesia", "التخدير"],
      ["Surgery", "الجراحة"],
      ["Radiology", "الأشعة"],
      ["Medical Imaging (MRI/CT)", "التصوير الطبي (رنين/مقطعي)"],
      ["Ultrasound / Sonography", "الموجات فوق الصوتية"],
      ["Laboratory Technology", "تقنيات المختبرات"],
      ["Phlebotomy", "سحب الدم"],
      ["Pharmacy", "الصيدلة"],
      ["Clinical Pharmacy", "الصيدلة السريرية"],
      ["Physiotherapy", "العلاج الطبيعي"],
      ["Occupational Therapy", "العلاج الوظيفي"],
      ["Speech Therapy", "علاج النطق"],
      ["Nutrition & Dietetics", "التغذية والحميات"],
      ["Mental Health & Psychology", "الصحة النفسية وعلم النفس"],
      ["Optometry", "فحص البصر"],
      ["Medical Coding (ICD-10/CPT)", "الترميز الطبي (ICD-10/CPT)"],
      ["Medical Billing", "الفوترة الطبية"],
      ["Health Insurance Claims", "مطالبات التأمين الصحي"],
      ["Electronic Medical Records (EMR)", "السجلات الطبية الإلكترونية"],
      ["Hospital Administration", "إدارة المستشفيات"],
      ["Healthcare Quality (JCI)", "جودة الرعاية الصحية (JCI)"],
      ["Infection Control", "مكافحة العدوى"],
      ["Basic Life Support (BLS)", "الإنعاش القلبي الأساسي"],
      ["Advanced Cardiac Life Support (ACLS)", "الإنعاش القلبي المتقدم"],
      ["First Aid", "الإسعافات الأولية"],
      ["DHA Licensing", "ترخيص هيئة الصحة بدبي"],
      ["MOH Licensing (UAE)", "ترخيص وزارة الصحة (الإمارات)"],
      ["DOH Licensing (Abu Dhabi)", "ترخيص دائرة الصحة (أبوظبي)"],
      ["SCFHS Licensing (Saudi Arabia)", "ترخيص الهيئة السعودية للتخصصات الصحية"],
      ["Prometric Exam Preparation", "التحضير لاختبار بروميتريك"],
      ["Home Healthcare", "الرعاية الصحية المنزلية"],
      ["Elderly Care", "رعاية المسنين"],
      ["Medical Terminology", "المصطلحات الطبية"],
      ["Telemedicine", "الطب عن بُعد"],
      ["Clinical Research", "البحوث السريرية"],
      ["Veterinary Medicine", "الطب البيطري"],
      ["Public Health", "الصحة العامة"],
      ["Medical Device Sales & Support", "مبيعات ودعم الأجهزة الطبية"],
    ],
  },
  {
    category: "Hospitality & F&B",
    skills: [
      ["Hotel Management", "إدارة الفنادق"],
      ["Front Office Operations", "عمليات مكتب الاستقبال"],
      ["Guest Relations", "علاقات الضيوف"],
      ["Concierge Services", "خدمات الكونسيرج"],
      ["Housekeeping", "التدبير المنزلي"],
      ["Reservations Management", "إدارة الحجوزات"],
      ["Revenue Management", "إدارة الإيرادات"],
      ["Opera PMS", "نظام أوبرا PMS"],
      ["Food & Beverage Service", "خدمة الأغذية والمشروبات"],
      ["Restaurant Management", "إدارة المطاعم"],
      ["Culinary Arts", "فنون الطهي"],
      ["Arabic Cuisine", "المطبخ العربي"],
      ["Indian Cuisine", "المطبخ الهندي"],
      ["Continental Cuisine", "المطبخ الأوروبي"],
      ["Asian Cuisine", "المطبخ الآسيوي"],
      ["Pastry & Baking", "الحلويات والمخبوزات"],
      ["Menu Planning", "تخطيط قوائم الطعام"],
      ["Kitchen Management", "إدارة المطبخ"],
      ["Food Cost Control", "مراقبة تكاليف الطعام"],
      ["Food Safety & HACCP", "سلامة الأغذية و HACCP"],
      ["Barista Skills", "مهارات الباريستا"],
      ["Bartending & Mixology", "تحضير المشروبات"],
      ["Banquet & Events Operations", "عمليات الحفلات والفعاليات"],
      ["Event Management", "إدارة الفعاليات"],
      ["Catering Management", "إدارة خدمات التموين"],
      ["Wedding Planning", "تنظيم حفلات الزفاف"],
      ["Travel & Tourism", "السفر والسياحة"],
      ["Tour Guiding", "الإرشاد السياحي"],
      ["Airline Ticketing (GDS/Amadeus)", "حجز تذاكر الطيران (Amadeus)"],
      ["Cabin Crew Services", "خدمات طاقم الضيافة الجوية"],
      ["Spa & Wellness Management", "إدارة السبا والعافية"],
      ["Fitness Training", "التدريب البدني"],
      ["Lifeguarding", "الإنقاذ المائي"],
      ["Micros POS", "نظام مايكروس POS"],
      ["Upselling (Hospitality)", "البيع الإضافي في الضيافة"],
      ["Cleaning & Sanitation", "التنظيف والتعقيم"],
      ["Laundry Operations", "عمليات المغسلة"],
      ["Butler Service", "خدمة كبير الخدم"],
      ["Valet & Doorman Services", "خدمات صف السيارات والبواب"],
    ],
  },
  {
    category: "Logistics & Supply Chain",
    skills: [
      ["Supply Chain Management", "إدارة سلسلة الإمداد"],
      ["Logistics Management", "إدارة الخدمات اللوجستية"],
      ["Procurement", "المشتريات"],
      ["Strategic Sourcing", "التوريد الاستراتيجي"],
      ["Vendor Negotiation", "التفاوض مع الموردين"],
      ["Purchase Order Management", "إدارة أوامر الشراء"],
      ["Inventory Management", "إدارة المخزون"],
      ["Warehouse Management", "إدارة المستودعات"],
      ["Warehouse Management Systems (WMS)", "أنظمة إدارة المستودعات"],
      ["Demand Planning", "تخطيط الطلب"],
      ["Freight Forwarding", "الشحن والتخليص"],
      ["Customs Clearance", "التخليص الجمركي"],
      ["Import & Export Documentation", "وثائق الاستيراد والتصدير"],
      ["Incoterms", "شروط التجارة الدولية Incoterms"],
      ["Sea Freight", "الشحن البحري"],
      ["Air Freight", "الشحن الجوي"],
      ["Land Transportation", "النقل البري"],
      ["Fleet Management", "إدارة الأساطيل"],
      ["Route Optimization", "تحسين المسارات"],
      ["Last-Mile Delivery", "التوصيل للميل الأخير"],
      ["Cold Chain Logistics", "لوجستيات سلسلة التبريد"],
      ["Dangerous Goods Handling (IATA/IMDG)", "التعامل مع البضائع الخطرة"],
      ["Shipping Documentation (B/L, AWB)", "وثائق الشحن (بوليصة/AWB)"],
      ["Order Fulfillment", "تنفيذ الطلبات"],
      ["Materials Management", "إدارة المواد"],
      ["Stock Auditing", "تدقيق المخزون"],
      ["Packing & Dispatch", "التعبئة والإرسال"],
      ["3PL Management", "إدارة الطرف الثالث اللوجستي"],
      ["Transport Planning", "تخطيط النقل"],
      ["Free Zone Operations (JAFZA/KIZAD)", "عمليات المناطق الحرة"],
      ["Dubai Trade Portal", "بوابة دبي التجارية"],
      ["E-commerce Fulfillment", "تنفيذ طلبات التجارة الإلكترونية"],
      ["Supplier Relationship Management", "إدارة علاقات الموردين"],
      ["Category Management", "إدارة الفئات"],
      ["Storekeeping", "أمانة المخازن"],
    ],
  },
  {
    category: "Legal & Compliance",
    skills: [
      ["Corporate Law", "قانون الشركات"],
      ["Commercial Law", "القانون التجاري"],
      ["Contract Drafting", "صياغة العقود"],
      ["Contract Negotiation", "التفاوض على العقود"],
      ["Legal Research", "البحث القانوني"],
      ["Litigation", "التقاضي"],
      ["Arbitration & Dispute Resolution", "التحكيم وحل النزاعات"],
      ["Employment Law", "قانون العمل"],
      ["Real Estate Law", "القانون العقاري"],
      ["Intellectual Property Law", "قانون الملكية الفكرية"],
      ["Regulatory Compliance", "الامتثال التنظيمي"],
      ["Corporate Governance", "حوكمة الشركات"],
      ["Company Formation (UAE/GCC)", "تأسيس الشركات (الإمارات/الخليج)"],
      ["Free Zone Licensing", "تراخيص المناطق الحرة"],
      ["Public Relations Officer (PRO) Services", "خدمات مندوب العلاقات العامة (PRO)"],
      ["Government Relations", "العلاقات الحكومية"],
      ["Legal Documentation", "التوثيق القانوني"],
      ["Legal Translation", "الترجمة القانونية"],
      ["Notarization & Attestation", "التوثيق والتصديق"],
      ["Due Diligence", "الفحص النافي للجهالة"],
      ["Data Protection (GDPR/PDPL)", "حماية البيانات (GDPR/PDPL)"],
      ["Banking Regulations", "اللوائح البنكية"],
      ["Sharia Law", "الشريعة الإسلامية"],
      ["Paralegal Support", "المساعدة القانونية"],
      ["Policy Development", "تطوير السياسات"],
      ["Ethics & Compliance Training", "تدريب الأخلاقيات والامتثال"],
      ["Sanctions Screening", "فحص العقوبات"],
      ["Insurance Law", "قانون التأمين"],
      ["Maritime Law", "القانون البحري"],
      ["Construction Law", "قانون الإنشاءات"],
    ],
  },
  {
    category: "Education & Training",
    skills: [
      ["Teaching", "التدريس"],
      ["Curriculum Development", "تطوير المناهج"],
      ["Lesson Planning", "تخطيط الدروس"],
      ["Classroom Management", "إدارة الصف"],
      ["Early Childhood Education", "تعليم الطفولة المبكرة"],
      ["Primary Education", "التعليم الابتدائي"],
      ["Secondary Education", "التعليم الثانوي"],
      ["Special Needs Education", "تعليم ذوي الاحتياجات الخاصة"],
      ["British Curriculum", "المنهج البريطاني"],
      ["American Curriculum", "المنهج الأمريكي"],
      ["IB Curriculum", "منهج البكالوريا الدولية"],
      ["CBSE Curriculum", "منهج CBSE"],
      ["Montessori Method", "طريقة مونتيسوري"],
      ["Teaching English (TEFL/TESOL)", "تدريس الإنجليزية (TEFL/TESOL)"],
      ["Arabic Language Teaching", "تدريس اللغة العربية"],
      ["Islamic Studies Teaching", "تدريس التربية الإسلامية"],
      ["Mathematics Teaching", "تدريس الرياضيات"],
      ["Science Teaching", "تدريس العلوم"],
      ["STEM Education", "تعليم STEM"],
      ["Educational Technology", "تكنولوجيا التعليم"],
      ["Learning Management Systems (Moodle/Canvas)", "أنظمة إدارة التعلم"],
      ["E-Learning Development", "تطوير التعلم الإلكتروني"],
      ["Instructional Design", "التصميم التعليمي"],
      ["Corporate Training", "التدريب المؤسسي"],
      ["Training Delivery", "تقديم التدريب"],
      ["Coaching & Mentoring", "التوجيه والإرشاد"],
      ["Student Assessment", "تقييم الطلاب"],
      ["Academic Advising", "الإرشاد الأكاديمي"],
      ["School Administration", "إدارة المدارس"],
      ["Tutoring", "الدروس الخصوصية"],
      ["Public Speaking", "الخطابة"],
      ["Workshop Facilitation", "تيسير ورش العمل"],
      ["Vocational Training", "التدريب المهني"],
      ["KHDA Standards", "معايير هيئة المعرفة والتنمية البشرية"],
      ["Articulate Storyline", "أرتيكيوليت ستوري لاين"],
    ],
  },
  {
    category: "Languages",
    skills: [
      ["Arabic", "العربية"],
      ["English", "الإنجليزية"],
      ["Hindi", "الهندية"],
      ["Urdu", "الأردية"],
      ["Malayalam", "المالايالامية"],
      ["Tamil", "التاميلية"],
      ["Telugu", "التيلوغوية"],
      ["Kannada", "الكانادا"],
      ["Bengali", "البنغالية"],
      ["Punjabi", "البنجابية"],
      ["Marathi", "الماراثية"],
      ["Gujarati", "الغوجاراتية"],
      ["Sinhala", "السنهالية"],
      ["Nepali", "النيبالية"],
      ["Tagalog (Filipino)", "التاغالوغية (الفلبينية)"],
      ["French", "الفرنسية"],
      ["Spanish", "الإسبانية"],
      ["German", "الألمانية"],
      ["Italian", "الإيطالية"],
      ["Portuguese", "البرتغالية"],
      ["Russian", "الروسية"],
      ["Turkish", "التركية"],
      ["Persian (Farsi)", "الفارسية"],
      ["Mandarin Chinese", "الصينية (الماندرين)"],
      ["Japanese", "اليابانية"],
      ["Korean", "الكورية"],
      ["Indonesian / Malay", "الإندونيسية / الماليزية"],
      ["Swahili", "السواحلية"],
      ["Amharic", "الأمهرية"],
      ["Pashto", "البشتو"],
      ["Dutch", "الهولندية"],
      ["Greek", "اليونانية"],
      ["Hebrew", "العبرية"],
      ["Sign Language", "لغة الإشارة"],
      ["Translation", "الترجمة"],
      ["Interpretation", "الترجمة الشفوية"],
      ["Arabic-English Translation", "الترجمة من العربية إلى الإنجليزية"],
      ["Transcription", "النسخ الصوتي"],
      ["Proofreading", "التدقيق اللغوي"],
      ["Localization", "التوطين اللغوي"],
    ],
  },
  {
    category: "Office & Administration",
    skills: [
      ["Microsoft Office", "مايكروسوفت أوفيس"],
      ["Microsoft Excel", "مايكروسوفت إكسل"],
      ["Microsoft Word", "مايكروسوفت وورد"],
      ["Microsoft PowerPoint", "مايكروسوفت باوربوينت"],
      ["Microsoft Outlook", "مايكروسوفت أوتلوك"],
      ["Microsoft Teams", "مايكروسوفت تيمز"],
      ["Google Workspace", "جوجل ووركسبيس"],
      ["Google Sheets", "جوجل شيتس"],
      ["Slack", "سلاك"],
      ["Zoom", "زووم"],
      ["Office Management", "إدارة المكاتب"],
      ["Executive Assistance", "المساعدة التنفيذية"],
      ["Personal Assistance", "المساعدة الشخصية"],
      ["Secretarial Skills", "المهارات السكرتارية"],
      ["Calendar Management", "إدارة الجداول والمواعيد"],
      ["Travel Arrangements", "ترتيبات السفر"],
      ["Meeting Coordination", "تنسيق الاجتماعات"],
      ["Minute Taking", "تدوين محاضر الاجتماعات"],
      ["Data Entry", "إدخال البيانات"],
      ["Typing (Arabic/English)", "الطباعة (عربي/إنجليزي)"],
      ["Document Control", "التحكم بالوثائق"],
      ["Records Management", "إدارة السجلات"],
      ["Filing & Archiving", "الأرشفة والحفظ"],
      ["Reception Duties", "مهام الاستقبال"],
      ["Front Desk Operations", "عمليات مكتب الاستقبال الأمامي"],
      ["Telephone Etiquette", "آداب التعامل الهاتفي"],
      ["Business Correspondence", "المراسلات التجارية"],
      ["Report Writing", "كتابة التقارير"],
      ["Email Management", "إدارة البريد الإلكتروني"],
      ["Expense Reporting", "تقارير المصروفات"],
      ["Office Supplies Procurement", "شراء مستلزمات المكتب"],
      ["Visitor Management", "إدارة الزوار"],
      ["Aconex", "أكونكس"],
      ["Adobe Acrobat", "أدوبي أكروبات"],
      ["Tender Documentation", "إعداد وثائق المناقصات"],
      ["Government Portal Transactions (Tasheel/Amer)", "معاملات البوابات الحكومية (تسهيل/آمر)"],
      ["Shorthand", "الاختزال"],
    ],
  },
  {
    category: "Soft Skills",
    skills: [
      ["Communication Skills", "مهارات التواصل"],
      ["Written Communication", "التواصل الكتابي"],
      ["Verbal Communication", "التواصل الشفهي"],
      ["Active Listening", "الاستماع الفعّال"],
      ["Teamwork", "العمل الجماعي"],
      ["Leadership", "القيادة"],
      ["Team Management", "إدارة الفرق"],
      ["People Management", "إدارة الأفراد"],
      ["Problem Solving", "حل المشكلات"],
      ["Critical Thinking", "التفكير النقدي"],
      ["Analytical Thinking", "التفكير التحليلي"],
      ["Decision Making", "اتخاذ القرارات"],
      ["Time Management", "إدارة الوقت"],
      ["Organizational Skills", "المهارات التنظيمية"],
      ["Attention to Detail", "الاهتمام بالتفاصيل"],
      ["Adaptability", "القدرة على التكيف"],
      ["Flexibility", "المرونة"],
      ["Creativity", "الإبداع"],
      ["Innovation", "الابتكار"],
      ["Emotional Intelligence", "الذكاء العاطفي"],
      ["Conflict Resolution", "حل النزاعات"],
      ["Interpersonal Skills", "المهارات الشخصية"],
      ["Multitasking", "تعدد المهام"],
      ["Work Under Pressure", "العمل تحت الضغط"],
      ["Self-Motivation", "التحفيز الذاتي"],
      ["Work Ethic", "أخلاقيات العمل"],
      ["Reliability", "الموثوقية"],
      ["Punctuality", "الالتزام بالمواعيد"],
      ["Cultural Awareness", "الوعي الثقافي"],
      ["Cross-Cultural Communication", "التواصل بين الثقافات"],
      ["Customer Focus", "التركيز على العميل"],
      ["Mentoring", "الإرشاد المهني"],
      ["Delegation", "التفويض"],
      ["Strategic Thinking", "التفكير الاستراتيجي"],
      ["Collaboration", "التعاون"],
      ["Networking", "بناء العلاقات المهنية"],
      ["Persuasion", "الإقناع"],
      ["Initiative", "المبادرة"],
      ["Accountability", "المسؤولية"],
      ["Confidentiality", "السرية"],
      ["Empathy", "التعاطف"],
      ["Resilience", "الصلابة النفسية"],
      ["Continuous Learning", "التعلم المستمر"],
      ["Remote Work Skills", "مهارات العمل عن بُعد"],
      ["Professionalism", "الاحترافية"],
    ],
  },
  {
    category: "Driving & Licences",
    skills: [
      ["UAE Driving Licence", "رخصة قيادة إماراتية"],
      ["Saudi Driving Licence", "رخصة قيادة سعودية"],
      ["Qatar Driving Licence", "رخصة قيادة قطرية"],
      ["Oman Driving Licence", "رخصة قيادة عُمانية"],
      ["Kuwait Driving Licence", "رخصة قيادة كويتية"],
      ["Bahrain Driving Licence", "رخصة قيادة بحرينية"],
      ["GCC Driving Licence", "رخصة قيادة خليجية"],
      ["Indian Driving Licence", "رخصة قيادة هندية"],
      ["International Driving Permit", "رخصة قيادة دولية"],
      ["Light Vehicle Licence", "رخصة مركبة خفيفة"],
      ["Heavy Vehicle Licence", "رخصة مركبة ثقيلة"],
      ["Heavy Truck Driving", "قيادة الشاحنات الثقيلة"],
      ["Bus Driving Licence", "رخصة قيادة الحافلات"],
      ["Motorcycle Licence", "رخصة الدراجات النارية"],
      ["Trailer Licence", "رخصة قيادة المقطورات"],
      ["Forklift Certification", "شهادة تشغيل الرافعة الشوكية"],
      ["Crane Operator Licence", "رخصة مشغل الرافعة"],
      ["Boom Truck Operation", "تشغيل شاحنة الرافعة"],
      ["Bobcat / Skid Steer Operation", "تشغيل البوبكات"],
      ["Reach Truck Operation", "تشغيل رافعة الوصول"],
      ["Defensive Driving", "القيادة الدفاعية"],
      ["Delivery Driving", "قيادة التوصيل"],
      ["Chauffeur Services", "خدمات السائق الخاص"],
      ["Ride-Hailing Driving (Careem/Uber)", "القيادة لتطبيقات النقل (كريم/أوبر)"],
      ["RTA Permit (Dubai)", "تصريح هيئة الطرق والمواصلات (دبي)"],
      ["Hazmat Transport Certification", "شهادة نقل المواد الخطرة"],
      ["Vehicle Maintenance", "صيانة المركبات"],
      ["Auto Mechanics", "ميكانيكا السيارات"],
      ["Auto Electrical", "كهرباء السيارات"],
      ["Auto Body & Paint", "سمكرة ودهان السيارات"],
      ["GPS Navigation", "التنقل بنظام GPS"],
      ["Marine Vessel Operation", "تشغيل السفن البحرية"],
      ["Seaman Book / STCW", "دفتر البحار / STCW"],
    ],
  },
  {
    category: "Certifications",
    skills: [
      ["PMP", "شهادة PMP"],
      ["CAPM", "شهادة CAPM"],
      ["PRINCE2 Certification", "شهادة PRINCE2"],
      ["Certified ScrumMaster (CSM)", "شهادة سكرم ماستر (CSM)"],
      ["PMI-ACP", "شهادة PMI-ACP"],
      ["SAFe Agilist", "شهادة SAFe"],
      ["CFA", "شهادة المحلل المالي المعتمد (CFA)"],
      ["ACCA", "شهادة ACCA"],
      ["CPA", "شهادة المحاسب القانوني المعتمد (CPA)"],
      ["CMA", "شهادة المحاسب الإداري المعتمد (CMA)"],
      ["CIA (Certified Internal Auditor)", "شهادة المدقق الداخلي المعتمد (CIA)"],
      ["CIMA", "شهادة CIMA"],
      ["FRM", "شهادة مدير المخاطر المالية (FRM)"],
      ["CISA", "شهادة CISA"],
      ["CISSP", "شهادة CISSP"],
      ["CISM", "شهادة CISM"],
      ["CEH (Certified Ethical Hacker)", "شهادة الهاكر الأخلاقي المعتمد (CEH)"],
      ["CompTIA Security+", "شهادة CompTIA Security+"],
      ["CompTIA A+", "شهادة CompTIA A+"],
      ["CompTIA Network+", "شهادة CompTIA Network+"],
      ["CCNA", "شهادة CCNA"],
      ["CCNP", "شهادة CCNP"],
      ["AWS Certified Solutions Architect", "شهادة AWS Solutions Architect"],
      ["AWS Certified Developer", "شهادة AWS Developer"],
      ["AWS Certified Cloud Practitioner", "شهادة AWS Cloud Practitioner"],
      ["Microsoft Azure Certification", "شهادة مايكروسوفت أزور"],
      ["Google Cloud Certification", "شهادة جوجل كلاود"],
      ["Certified Kubernetes Administrator (CKA)", "شهادة مسؤول كوبرنيتس (CKA)"],
      ["ITIL Foundation", "شهادة ITIL Foundation"],
      ["Microsoft Certified Professional", "شهادة مايكروسوفت المعتمدة"],
      ["Oracle Certified Professional", "شهادة أوراكل المعتمدة"],
      ["Salesforce Certification", "شهادة سيلزفورس"],
      ["SAP Certification", "شهادة ساب"],
      ["Six Sigma Green Belt", "الحزام الأخضر ستة سيجما"],
      ["Six Sigma Black Belt", "الحزام الأسود ستة سيجما"],
      ["Lean Six Sigma", "لين ستة سيجما"],
      ["NEBOSH IGC", "شهادة نيبوش IGC"],
      ["NEBOSH Diploma", "دبلوم نيبوش"],
      ["IOSH Managing Safely", "شهادة IOSH"],
      ["OSHA 30-Hour", "شهادة أوشا 30 ساعة"],
      ["OSHA 10-Hour", "شهادة أوشا 10 ساعات"],
      ["ISO Lead Auditor", "شهادة المدقق الرئيسي ISO"],
      ["ISO 9001 Lead Auditor", "المدقق الرئيسي ISO 9001"],
      ["ISO 45001 Lead Auditor", "المدقق الرئيسي ISO 45001"],
      ["CSP (Certified Safety Professional)", "شهادة أخصائي السلامة المعتمد (CSP)"],
      ["First Aid Certification", "شهادة الإسعافات الأولية"],
      ["Fire Warden Certification", "شهادة مراقب الحرائق"],
      ["H2S Awareness", "شهادة التوعية بغاز كبريتيد الهيدروجين"],
      ["BOSIET", "شهادة BOSIET"],
      ["Confined Space Entry", "شهادة الدخول إلى الأماكن المحصورة"],
      ["Working at Heights", "شهادة العمل على ارتفاعات"],
      ["API 510 / 570 / 653", "شهادات API 510/570/653"],
      ["AWS CWI (Certified Welding Inspector)", "شهادة مفتش اللحام المعتمد (CWI)"],
      ["ASNT NDT Level II", "شهادة ASNT NDT المستوى الثاني"],
      ["CSWIP", "شهادة CSWIP"],
      ["CIPD", "شهادة CIPD"],
      ["SHRM-CP / SHRM-SCP", "شهادة SHRM"],
      ["PHR / SPHR", "شهادة PHR / SPHR"],
      ["CIPS", "شهادة CIPS"],
      ["CSCP (Supply Chain)", "شهادة CSCP"],
      ["CPIM", "شهادة CPIM"],
      ["CLTD", "شهادة CLTD"],
      ["Google Ads Certification", "شهادة إعلانات جوجل"],
      ["Google Analytics Certification", "شهادة جوجل أناليتكس"],
      ["HubSpot Certification", "شهادة هاب سبوت"],
      ["Meta Blueprint Certification", "شهادة ميتا بلوبرنت"],
      ["CBAP", "شهادة CBAP"],
      ["TOGAF", "شهادة TOGAF"],
      ["Certified Data Professional", "شهادة أخصائي البيانات المعتمد"],
      ["TensorFlow Developer Certificate", "شهادة مطور تنسرفلو"],
      ["Chartered Engineer (CEng)", "مهندس معتمد (CEng)"],
      ["Society of Engineers UAE Membership", "عضوية جمعية المهندسين الإماراتية"],
      ["Saudi Council of Engineers", "الهيئة السعودية للمهندسين"],
      ["LEED Accredited Professional", "أخصائي LEED المعتمد"],
      ["RICS Chartered Surveyor", "مساح معتمد RICS"],
      ["CFP (Certified Financial Planner)", "شهادة المخطط المالي المعتمد (CFP)"],
      ["CAMS (Anti-Money Laundering)", "شهادة CAMS لمكافحة غسل الأموال"],
      ["CELTA", "شهادة CELTA"],
      ["IELTS", "اختبار IELTS"],
      ["TOEFL", "اختبار TOEFL"],
      ["Certified Coach (ICF)", "مدرب معتمد (ICF)"],
      ["Food Safety Level 2/3", "شهادة سلامة الأغذية المستوى 2/3"],
      ["HACCP Certification", "شهادة HACCP"],
      ["ServSafe", "شهادة ServSafe"],
      ["Registered Nurse (RN) Licence", "ترخيص ممرض مسجل (RN)"],
      ["PALS", "شهادة الإنعاش المتقدم للأطفال (PALS)"],
      ["CPHQ", "شهادة CPHQ"],
      ["Certified Medical Coder (CPC)", "شهادة المرمز الطبي المعتمد (CPC)"],
      ["Certified Trainer (TOT)", "مدرب معتمد (TOT)"],
    ],
  },
];
